# Generated by Django 2.2.10 on 2020-02-13 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0043_auto_20200213_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighSchoolStudentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('civility', models.SmallIntegerField(choices=[(1, 'Mr'), (2, 'Mrs')], default=1, verbose_name='Civility')),
                ('phone', models.CharField(max_length=14, verbose_name='Phone number')),
                ('level', models.SmallIntegerField(choices=[(1, 'Pupil in year 12 / 11th grade student'), (2, 'Pupil in year 13 / 12th grade student'), (3, 'Above A Level / High-School Degree')], default=1, verbose_name='Level')),
                ('bachelor_type', models.SmallIntegerField(choices=[(1, 'General'), (2, 'Technological'), (3, 'Professional'), (4, 'DAEU')], default=1, verbose_name='Bachelor type')),
                ('professional_bachelor_mention', models.CharField(blank=True, max_length=128, null=True, verbose_name='Professional bachelor mention')),
                ('post_bachelor_level', models.SmallIntegerField(blank=True, choices=[(1, 'BTS1'), (2, 'BTS2'), (3, 'BTSA1'), (4, 'BTSA2'), (5, 'Other')], default=1, null=True, verbose_name='Level')),
                ('origin_bachelor_type', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Bachelor type')),
                ('current_diploma', models.CharField(blank=True, max_length=128, null=True, verbose_name='Current diploma')),
                ('visible_immersion_registrations', models.BooleanField(default=False, verbose_name='Allow students from my school to see my registrations')),
                ('visible_email', models.BooleanField(default=False, verbose_name='Allow students from my school to see my email address')),
                ('allowed_global_registrations', models.SmallIntegerField(blank=True, null=True, verbose_name='Number of allowed year registrations')),
                ('allowed_first_semester_registrations', models.SmallIntegerField(blank=True, null=True, verbose_name='Number of allowed registrations for second semester')),
                ('allowed_second_semester_registrations', models.SmallIntegerField(blank=True, null=True, verbose_name='Number of allowed registrations for first semester')),
                ('general_bachelor_teachings', models.ManyToManyField(blank=True, related_name='student_records', to='core.GeneralBachelorTeaching', verbose_name='Components')),
                ('highschool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='core.HighSchool', verbose_name='High school')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_record', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('technological_bachelor_mention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_records', to='core.BachelorMention', verbose_name='Technological bachelor mention')),
            ],
        ),
    ]
