# Generated by Django 2.2.9 on 2020-02-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0002_highschoolstudentrecord_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschoolstudentrecord',
            name='validation',
            field=models.SmallIntegerField(choices=[(1, 'To validate'), (2, 'Validated'), (3, 'Rejected')], default=1, verbose_name='Civility'),
        ),
    ]
