# Generated by Django 2.2.10 on 2020-02-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0003_auto_20200214_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Phone number'),
        ),
    ]
