# Generated by Django 2.2.9 on 2020-02-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0003_highschoolstudentrecord_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='validation',
            field=models.SmallIntegerField(choices=[(1, 'To validate'), (2, 'Validated'), (3, 'Rejected')], default=1, verbose_name='Validation'),
        ),
    ]
