# Generated by Django 2.2.9 on 2020-02-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0004_auto_20200217_1202'),
        ('immersion', '0004_auto_20200217_1445'),
    ]

    operations = [
    ]
