# Generated by Django 2.2.10 on 2020-02-19 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('immersion', '0005_merge_20200218_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='origin_bachelor_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'General'), (2, 'Technological'), (3, 'Professional'), (4, 'DAEU')], default=1, null=True, verbose_name='Origin bachelor type'),
        ),
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='post_bachelor_level',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'BTS1'), (2, 'BTS2'), (3, 'BTSA1'), (4, 'BTSA2'), (5, 'Other')], default=1, null=True, verbose_name='Post bachelor level'),
        ),
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='high_school_student_record', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_institution', models.CharField(max_length=256, verbose_name='Home institution')),
                ('civility', models.SmallIntegerField(choices=[(1, 'Mr'), (2, 'Mrs')], default=1, verbose_name='Civility')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Phone number')),
                ('level', models.SmallIntegerField(choices=[(1, 'Licence 1 (1st year above A level)'), (2, 'Licence 2 (2nd year above A level)'), (3, 'Licence 3 (3rd year above A level)'), (4, 'BTEC 1'), (5, 'BTEC 2'), (6, 'Other')], default=1, verbose_name='Level')),
                ('origin_bachelor_type', models.SmallIntegerField(choices=[(1, 'General'), (2, 'Technological'), (3, 'Professional'), (4, 'DAEU')], default=1, verbose_name='Origin bachelor type')),
                ('current_diploma', models.CharField(blank=True, max_length=128, null=True, verbose_name='Current diploma')),
                ('allowed_global_registrations', models.SmallIntegerField(blank=True, null=True, verbose_name='Number of allowed year registrations')),
                ('allowed_first_semester_registrations', models.SmallIntegerField(blank=True, null=True, verbose_name='Number of allowed registrations for second semester')),
                ('allowed_second_semester_registrations', models.SmallIntegerField(blank=True, null=True, verbose_name='Number of allowed registrations for first semester')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_record', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
    ]
