# Generated by Django 2.2.10 on 2020-02-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0006_auto_20200219_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highschoolstudentrecord',
            name='allowed_first_semester_registrations',
        ),
        migrations.RemoveField(
            model_name='highschoolstudentrecord',
            name='allowed_global_registrations',
        ),
        migrations.RemoveField(
            model_name='highschoolstudentrecord',
            name='allowed_second_semester_registrations',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='allowed_first_semester_registrations',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='allowed_global_registrations',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='allowed_second_semester_registrations',
        ),
    ]
