# Generated by Django 2.2.10 on 2020-03-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0007_auto_20200220_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschoolstudentrecord',
            name='allowed_first_semester_registrations',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Number of allowed registrations for second semester'),
        ),
        migrations.AddField(
            model_name='highschoolstudentrecord',
            name='allowed_global_registrations',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Number of allowed year registrations'),
        ),
        migrations.AddField(
            model_name='highschoolstudentrecord',
            name='allowed_second_semester_registrations',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Number of allowed registrations for first semester'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='allowed_first_semester_registrations',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Number of allowed registrations for second semester'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='allowed_global_registrations',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Number of allowed year registrations'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='allowed_second_semester_registrations',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Number of allowed registrations for first semester'),
        ),
    ]
