# Generated by Django 2.2.11 on 2020-04-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0008_auto_20200304_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highschoolstudentrecord',
            options={'verbose_name': 'High school student record', 'verbose_name_plural': 'High school student records'},
        ),
        migrations.AlterModelOptions(
            name='studentrecord',
            options={'verbose_name': 'Student record', 'verbose_name_plural': 'Student records'},
        ),
    ]
