# Generated by Django 2.2.11 on 2020-04-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0009_auto_20200402_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrecord',
            name='home_institution',
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='uai_code',
            field=models.CharField(default='', max_length=256, verbose_name='Home institution code'),
            preserve_default=False,
        ),
    ]
