# Generated by Django 2.2.12 on 2020-04-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0011_auto_20200421_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschoolstudentrecord',
            name='solved_duplicates',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Solved duplicates list'),
        ),
    ]
