# Generated by Django 3.2.7 on 2021-09-14 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20210914_1036'),
        ('immersion', '0012_highschoolstudentrecord_solved_duplicates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='technological_bachelor_mention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_records', to='core.bachelormention', verbose_name='Technological bachelor series'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
