# Generated by Django 3.2.8 on 2021-10-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0014_alter_highschoolstudentrecord_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'Première'), (2, 'Terminale'), (3, 'Post-bac')], default=1, verbose_name='Level'),
        ),
    ]
