# Generated by Django 3.2.8 on 2021-10-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0015_alter_highschoolstudentrecord_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'Pupil in year 12 / 11th grade student'), (2, 'Pupil in year 13 / 12th grade student'), (3, 'Above A Level / High-School Degree')], default=1, verbose_name='Level'),
        ),
    ]
