# Generated by Django 3.2.8 on 2021-10-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0016_auto_20211008_1613'),
        ('immersion', '0017_alter_highschoolstudentrecord_level'),
    ]

    operations = [
    ]
