# Generated by Django 3.2.8 on 2021-11-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0019_alter_highschoolstudentrecord_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='allowed_first_semester_registrations',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Number of allowed registrations for first semester (excluding visits and events)'),
        ),
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='allowed_second_semester_registrations',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Number of allowed registrations for second semester (excluding visits and events)'),
        ),
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='level',
            field=models.SmallIntegerField(choices=[(4, 'Pupil in year 11 / 10th grade student'), (1, 'Première'), (2, 'Terminale'), (3, 'Post-bac')], default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='allowed_first_semester_registrations',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Number of allowed registrations for second semester (excluding visits and events)'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='allowed_global_registrations',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Number of allowed year registrations (excluding visits and events)'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='allowed_second_semester_registrations',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Number of allowed registrations for first semester (excluding visits and events)'),
        ),
    ]
