# Generated by Django 3.2.8 on 2021-11-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0020_alter_highschoolstudentrecord_level'),
        ('immersion', '0020_auto_20211129_1157'),
    ]

    operations = [
    ]
