# Generated by Django 3.2.8 on 2021-11-29 15:50

from django.db import migrations, models


def update_level(apps, shema_editor):
    HSRecord = apps.get_model("immersion", "HighSchoolStudentRecord")

    for instance in HSRecord.objects.all():
        instance.level = instance.level + 1
        instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0020_auto_20211129_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'Seconde'), (2, 'Première'), (3, 'Terminale'), (4, 'Post-bac')], default=1, verbose_name='Level'),
        ),
        migrations.RunPython(update_level, reverse_code=migrations.RunPython.noop),
    ]
