# Generated by Django 3.2.8 on 2021-12-01 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0021_alter_highschoolstudentrecord_level'),
        ('immersion', '0021_merge_20211130_1557'),
    ]

    operations = [
    ]
