# Generated by Django 3.2.8 on 2021-12-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_auto_20211220_1840'),
        ('immersion', '0022_merge_20211201_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_school_student_record', to='core.highschoollevel', verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='post_bachelor_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='high_school_student_record', to='core.postbachelorlevel', verbose_name='Post bachelor level'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_record', to='core.studentlevel', verbose_name='Level'),
        ),
    ]
