# Generated by Django 3.2.8 on 2022-01-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0023_auto_20211220_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highschoolstudentrecord',
            name='civility',
        ),
    ]
