# Generated by Django 3.2.8 on 2021-12-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0023_visitorrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorrecord',
            name='validation',
            field=models.SmallIntegerField(choices=[(1, 'To validate'), (2, 'Validated'), (3, 'Rejected')], default=1, verbose_name='Validation'),
        ),
    ]
