# Generated by Django 3.2.8 on 2022-01-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0024_remove_highschoolstudentrecord_civility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrecord',
            name='civility',
        ),
    ]
