# Generated by Django 3.2.18 on 2023-03-24 07:58

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_auto_20230324_0858'),
        ('immersion', '0028_visitorrecord_parental_auth_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highschoolstudentrecord',
            name='allowed_first_semester_registrations',
        ),
        migrations.RemoveField(
            model_name='highschoolstudentrecord',
            name='allowed_global_registrations',
        ),
        migrations.RemoveField(
            model_name='highschoolstudentrecord',
            name='allowed_second_semester_registrations',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='allowed_first_semester_registrations',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='allowed_global_registrations',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='allowed_second_semester_registrations',
        ),
        migrations.RemoveField(
            model_name='visitorrecord',
            name='allowed_first_semester_registrations',
        ),
        migrations.RemoveField(
            model_name='visitorrecord',
            name='allowed_global_registrations',
        ),
        migrations.RemoveField(
            model_name='visitorrecord',
            name='allowed_second_semester_registrations',
        ),
        migrations.CreateModel(
            name='VisitorRecordQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_immersions', models.PositiveIntegerField(default=1, verbose_name='Allowed immersions')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.period')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immersion.visitorrecord')),
            ],
            options={
                'verbose_name': 'Visitor record / Period quota',
                'verbose_name_plural': 'Visitor record / Period quotas',
            },
        ),
        migrations.CreateModel(
            name='StudentRecordQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_immersions', models.PositiveIntegerField(default=1, verbose_name='Allowed immersions')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.period')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immersion.studentrecord')),
            ],
            options={
                'verbose_name': 'Student record / Period quota',
                'verbose_name_plural': 'Student record / Period quotas',
            },
        ),
        migrations.CreateModel(
            name='HighSchoolStudentRecordQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_immersions', models.PositiveIntegerField(default=1, verbose_name='Allowed immersions')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.period')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immersion.highschoolstudentrecord')),
            ],
            options={
                'verbose_name': 'High school student record / Period quota',
                'verbose_name_plural': 'High school student record / Period quotas',
            },
        ),
        migrations.AddField(
            model_name='highschoolstudentrecord',
            name='allowed_immersions',
            field=models.ManyToManyField(through='immersion.HighSchoolStudentRecordQuota', to='core.Period'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='allowed_immersions',
            field=models.ManyToManyField(through='immersion.StudentRecordQuota', to='core.Period'),
        ),
        migrations.AddField(
            model_name='visitorrecord',
            name='allowed_immersions',
            field=models.ManyToManyField(through='immersion.VisitorRecordQuota', to='core.Period'),
        ),
        migrations.AddConstraint(
            model_name='visitorrecordquota',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('record', 'period'), name='unique_visitor_record_period'),
        ),
        migrations.AddConstraint(
            model_name='studentrecordquota',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('record', 'period'), name='unique_student_record_period'),
        ),
        migrations.AddConstraint(
            model_name='highschoolstudentrecordquota',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('record', 'period'), name='unique_high_school_student_record_period'),
        ),
    ]
