# Generated by Django 3.2.16 on 2023-03-28 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0029_auto_20230324_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolstudentrecordquota',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='immersion.highschoolstudentrecord'),
        ),
        migrations.AlterField(
            model_name='studentrecordquota',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='immersion.studentrecord'),
        ),
        migrations.AlterField(
            model_name='visitorrecordquota',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='immersion.visitorrecord'),
        ),
    ]
