# Generated by Django 3.2.16 on 2023-03-29 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_auto_20230328_1307'),
        ('immersion', '0030_auto_20230328_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_records', to='core.highereducationinstitution', verbose_name='Home institution'),
        ),
    ]
