# Generated by Django 3.2.18 on 2023-04-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0031_studentrecord_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschoolstudentrecord',
            name='allow_high_school_consultation',
            field=models.BooleanField(default=False, verbose_name='Allow my high school to view my immersions and attendance certificates'),
        ),
    ]
