# Generated by Django 3.2.18 on 2023-04-13 12:04
from datetime import datetime

from django.db import migrations, models
from django.utils.timezone import get_current_timezone


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0032_highschoolstudentrecord_allow_high_school_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschoolstudentrecord',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now(tz=get_current_timezone()), verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highschoolstudentrecord',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification date'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now(tz=get_current_timezone()), verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification date'),
        ),
        migrations.AddField(
            model_name='visitorrecord',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now(tz=get_current_timezone()), verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitorrecord',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification date'),
        ),
    ]
