# Generated by Django 3.2.18 on 2023-04-13 14:28

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion
import immersionlyceens.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_auto_20230413_1628'),
        ('immersion', '0032_highschoolstudentrecord_allow_high_school_consultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorRecordDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last updated date')),
                ('document', models.FileField(help_text='Seulement des fichiers de type (doc, pdf, xls, ods, odt, docx, xlsx). Taille max : 20,0\xa0Mio', upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Document')),
                ('validity_date', models.DateField(blank=True, null=True, verbose_name='Valid until')),
                ('for_minors', models.BooleanField(default=True, verbose_name='For minors')),
                ('mandatory', models.BooleanField(default=True, verbose_name='Mandatory')),
                ('requires_validity_date', models.BooleanField(default=True, verbose_name='Requires a validity date')),
                ('attestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.attestationdocument')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestation', to='immersion.visitorrecord')),
            ],
            options={
                'verbose_name': 'Visitor record / Attestation document',
                'verbose_name_plural': 'Visitor record / Attestation documents',
            },
        ),
        migrations.CreateModel(
            name='HighSchoolStudentRecordDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last updated date')),
                ('document', models.FileField(help_text='Seulement des fichiers de type (doc, pdf, xls, ods, odt, docx, xlsx). Taille max : 20,0\xa0Mio', upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Document')),
                ('validity_date', models.DateField(blank=True, null=True, verbose_name='Valid until')),
                ('for_minors', models.BooleanField(default=True, verbose_name='For minors')),
                ('mandatory', models.BooleanField(default=True, verbose_name='Mandatory')),
                ('requires_validity_date', models.BooleanField(default=True, verbose_name='Requires a validity date')),
                ('attestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.attestationdocument')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestation', to='immersion.highschoolstudentrecord')),
            ],
            options={
                'verbose_name': 'High school student record / Attestation document',
                'verbose_name_plural': 'High school student record / Attestation documents',
            },
        ),
        migrations.AddField(
            model_name='highschoolstudentrecord',
            name='attestation_documents',
            field=models.ManyToManyField(through='immersion.HighSchoolStudentRecordDocument', to='core.AttestationDocument'),
        ),
        migrations.AddField(
            model_name='visitorrecord',
            name='attestation_documents',
            field=models.ManyToManyField(through='immersion.VisitorRecordDocument', to='core.AttestationDocument'),
        ),
        migrations.AddConstraint(
            model_name='visitorrecorddocument',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('record', 'attestation'), name='unique_visitor_record_document'),
        ),
        migrations.AddConstraint(
            model_name='highschoolstudentrecorddocument',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('record', 'attestation'), name='unique_high_school_student_record_document'),
        ),
    ]
