# Generated by Django 3.2.18 on 2023-04-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0033_auto_20230413_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorrecord',
            name='civil_liability_insurance',
        ),
        migrations.RemoveField(
            model_name='visitorrecord',
            name='identity_document',
        ),
        migrations.RemoveField(
            model_name='visitorrecord',
            name='parental_auth_document',
        ),
    ]
