# Generated by Django 3.2.18 on 2023-04-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0033_auto_20230413_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschoolstudentrecord',
            name='validation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validation date'),
        ),
    ]
