# Generated by Django 3.2.18 on 2023-04-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0034_auto_20230418_1024'),
        ('immersion', '0035_auto_20230414_1326'),
    ]

    operations = [
    ]
