# Generated by Django 3.2.18 on 2023-04-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0036_merge_0034_auto_20230418_1024_0035_auto_20230414_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorrecord',
            name='validation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validation date'),
        ),
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='validation',
            field=models.SmallIntegerField(
                choices=[(0, 'To complete'), (1, 'To validate'), (2, 'Validated'), (3, 'Rejected')], default=0,
                verbose_name='Validation'),
        ),
        migrations.AlterField(
            model_name='visitorrecord',
            name='validation',
            field=models.SmallIntegerField(
                choices=[(0, 'To complete'), (1, 'To validate'), (2, 'Validated'), (3, 'Rejected')], default=0,
                verbose_name='Validation'),
        ),
    ]
