# Generated by Django 3.2.18 on 2023-04-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0037_auto_20230424_1801'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='highschoolstudentrecorddocument',
            name='unique_high_school_student_record_document',
        ),
        migrations.RemoveConstraint(
            model_name='visitorrecorddocument',
            name='unique_visitor_record_document',
        ),
        migrations.AddField(
            model_name='highschoolstudentrecorddocument',
            name='deposit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deposit date'),
        ),
        migrations.AddField(
            model_name='visitorrecorddocument',
            name='deposit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deposit date'),
        ),
        migrations.AddField(
            model_name='highschoolstudentrecorddocument',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Archive status'),
        ),
        migrations.AddField(
            model_name='visitorrecorddocument',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Archive status'),
        ),
        migrations.AddConstraint(
            model_name='highschoolstudentrecorddocument',
            constraint=models.UniqueConstraint(condition=models.Q(('archive', False)), fields=('record', 'attestation', 'archive'), name='unique_high_school_student_record_document'),
        ),
        migrations.AddConstraint(
            model_name='visitorrecorddocument',
            constraint=models.UniqueConstraint(condition=models.Q(('archive', False)), fields=('record', 'attestation', 'archive'), name='unique_visitor_record_document'),
        ),
    ]
