# Generated by Django 3.2.18 on 2023-05-09 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_auto_20230509_0942'),
        ('immersion', '0039_auto_20230504_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='bachelor_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'pre_bachelor_level': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_records', to='core.bachelortype', verbose_name='Bachelor type'),
        ),
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='origin_bachelor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.bachelortype', verbose_name='Origin bachelor type'),
        ),
    ]
