# Generated by Django 3.2.18 on 2023-05-09 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_auto_20230509_0942'),
        ('immersion', '0040_auto_20230509_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='origin_bachelor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.bachelortype', verbose_name='Bachelor type'),
        ),
    ]
