# Generated by Django 5.0.4 on 2024-04-11 14:26

import django.db.models.deletion
import immersionlyceens.apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0213_alter_slot_allowed_bachelor_mentions_and_more'),
        ('immersion', '0042_auto_20230510_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='class_name',
            field=models.CharField(max_length=32, null=True, verbose_name='Class name'),
        ),
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='highschool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='core.highschool', verbose_name='High school'),
        ),
        migrations.AlterField(
            model_name='highschoolstudentrecord',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='high_school_student_record', to='core.highschoollevel', verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='highschoolstudentrecorddocument',
            name='document',
            field=models.FileField(help_text='Seulement des fichiers de type (png, jpeg, jpg, pdf, doc, docx, odt). Taille max : 20,0\xa0Mio', upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_record', to='core.studentlevel', verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='origin_bachelor_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.bachelortype', verbose_name='Bachelor type'),
        ),
        migrations.AlterField(
            model_name='visitorrecord',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='visitorrecord',
            name='motivation',
            field=models.TextField(null=True, verbose_name='Motivation'),
        ),
        migrations.AlterField(
            model_name='visitorrecorddocument',
            name='document',
            field=models.FileField(help_text='Seulement des fichiers de type (png, jpeg, jpg, pdf, doc, docx, odt). Taille max : 20,0\xa0Mio', upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Document'),
        ),
    ]
