# Generated by Django 5.0.4 on 2024-04-22 10:11

import immersionlyceens.apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0043_alter_highschoolstudentrecord_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolstudentrecorddocument',
            name='document',
            field=models.FileField(help_text='Uniquement des fichiers de type (png, jpeg, jpg, pdf, doc, docx, odt). Taille max : 20,0\xa0Mio', upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='visitorrecorddocument',
            name='document',
            field=models.FileField(help_text='Uniquement des fichiers de type (png, jpeg, jpg, pdf, doc, docx, odt). Taille max : 20,0\xa0Mio', upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Document'),
        ),
    ]
