# Generated by Django 5.0.12 on 2025-02-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0045_alter_highschoolstudentrecord_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='validation',
            field=models.SmallIntegerField(choices=[(0, 'To complete'), (2, 'Validated'), (5, 'Initialization (to complete)')], default=0, verbose_name='Validation'),
        ),
    ]
