# Generated by Django 5.0.14 on 2025-07-31 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0260_visitortype_alter_establishment_data_source_plugin'),
        ('immersion', '0046_studentrecord_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorrecord',
            name='visitor_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='core.visitortype', verbose_name='Visitor type'),
        ),
    ]
