# Generated by Django 5.0.14 on 2025-07-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0046_studentrecord_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschoolstudentrecord',
            name='disability',
            field=models.BooleanField(default=False, verbose_name='Disabled person'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='disability',
            field=models.BooleanField(default=False, verbose_name='Disabled person'),
        ),
        migrations.AddField(
            model_name='visitorrecord',
            name='disability',
            field=models.BooleanField(default=False, verbose_name='Disabled person'),
        ),
    ]
