# Generated by Django 5.0.14 on 2025-08-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0049_visitorrecord_visitor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolstudentrecorddocument',
            name='validity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Validity date'),
        ),
    ]
