# Generated by Django 5.0.14 on 2025-09-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0050_alter_highschoolstudentrecorddocument_validity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorrecord',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Rejection reason'),
        ),
    ]
