# Generated by Django 5.0.14 on 2025-09-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0051_visitorrecord_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschoolstudentrecord',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Rejection reason'),
        ),
    ]
