# Generated by Django 5.0.14 on 2025-09-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0052_highschoolstudentrecord_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolstudentrecorddocument',
            name='validity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Valid until'),
        ),
    ]
