# Generated by Django 5.0.14 on 2026-02-18 08:40

import immersionlyceens.apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion', '0053_alter_highschoolstudentrecorddocument_validity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolstudentrecorddocument',
            name='document',
            field=models.FileField(help_text='Uniquement des fichiers de type (svg, png, jpeg, jpg, pdf, doc, docx, odt). Taille max : 20,0\xa0Mio', upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='visitorrecorddocument',
            name='document',
            field=models.FileField(help_text='Uniquement des fichiers de type (svg, png, jpeg, jpg, pdf, doc, docx, odt). Taille max : 20,0\xa0Mio', upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Document'),
        ),
    ]
