# pull buster slim python image
FROM python:3.8-slim-buster

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


# packages required for setting up WSGI & psycopg2
RUN apt-get update
RUN apt-get install -y --no-install-recommends gcc libc-dev python3-dev postgresql-dev musl-dev

# install uWSGI lts version
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy entrypoint.sh
COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# copy project
COPY ../../../. .

# run entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
