
stages:
  - test

services:
  - postgres

variables:
  POSTGRES_DB: immersionlyceens-test
  POSTGRES_USER: immersionlyceens
  POSTGRES_PASSWORD: immersionlyceens

before_script:
  - apt-get update && apt-get install -y build-essential libffi-dev libxslt1-dev libxml2-dev zlib1g-dev libcairo2 libpango1.0-0 libpq-dev

unittest:
  stage: test
  tags:
    - python3.7
  script:
    - pip3 install tox
    - tox

safety:
  stage: test
  tags:
    - python3.7
  script:
    - pip3 install -r requirements/dev.txt
    - safety check
  only:
    - develop
    - master
