version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: ./deploy/docker/app/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    restart: always
    env_file:
      - ./deploy/docker/.env.dev
    environment:
      - DEFAULT_DB_HOST=0.0.0.0
    links:
      - db:db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:12
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=immersion
      - POSTGRES_PASSWORD=immersion
      - POSTGRES_DB=immersion
    ports:
      - 5432:5432
    restart: always

    healthcheck:
      test: "pg_isready --username=immersion && psql --username=immersion --list"
      timeout: 30s
      retries: 20

    networks:
      default:
        aliases:
          - db

volumes:
  postgres_data:
