version: "3.8"

services:
  web:
    container_name: immersion-app-demo
    networks:
      - immersion-demo-net
    build:
      context: ./
      dockerfile: ./deploy/docker/app/Dockerfile.demo
    volumes:
      - static_volume:/home/immersion/web/staticfiles
      - media_volume:/home/immersion/web/mediafiles
    expose:
      - 8000
    restart: always
    env_file:
      - ./deploy/docker/.env.demo
    depends_on:
      - db
  db:
    container_name: immersion-db-demo
    networks:
      - immersion-demo-net
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./deploy/docker/.env.demo.db
    ports:
      - 5432:5432
  nginx:
    container_name: immersion-nginx-demo
    networks:
      - immersion-demo-net
    build: ./deploy/docker/nginx
    restart: always
    env_file:
      - ./deploy/docker/.env.demo
    volumes:
      - static_volume:/home/immersion/web/staticfiles
      - media_volume:/home/immersion/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  immersion-demo-net:
