map_settings = {
    'default_db_host': "DATABASES['default']['HOST']",
    'default_db_user': "DATABASES['default']['USER']",
    'default_db_password': "DATABASES['default']['PASSWORD']",
    'default_db_name': "DATABASES['default']['NAME']",
    'secret_key': "SECRET_KEY",
    'cas_redirect_url': "CAS_REDIRECT_URL",
    'release': "RELEASE",
    's3_access_key': "AWS_ACCESS_KEY_ID",
    's3_secret_key': "AWS_SECRET_ACCESS_KEY",
    's3_bucket': "AWS_STORAGE_BUCKET_NAME",
    's3_endpoint': "AWS_S3_ENDPOINT_URL",
    'matomo_url': "MATOMO_URL",
    'matomo_site_id': "MATOMO_SITE_ID",
    'use_unistra_theme': "UNISTRA",
    'email_host': "EMAIL_HOST",
    'email_port': "EMAIL_PORT",
    'email_use_tls': "EMAIL_USE_TLS",
    'email_host_user': "EMAIL_HOST_USER",
    'email_host_password': "EMAIL_HOST_PASSWORD",
    'force_email_address': "FORCE_EMAIL_ADDRESS",
    'default_from_email': "DEFAULT_FROM_EMAIL",
    'extra_locale_path': "EXTRA_LOCALE_PATH",
    'csrf_trusted_origins': "CSRF_TRUSTED_ORIGINS",
    'uai_api_url': "UAI_API_URL",
    'uai_api_auth_header': "UAI_API_AUTH_HEADER",
}