# Generated by Django 2.2.9 on 2020-01-14 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='campus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='core.Campus', verbose_name='Campus'),
        ),
    ]
