# Generated by Django 2.2.9 on 2020-01-13 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('campus', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Campus', verbose_name='Campus')),
            ],
        ),
    ]
