# Generated by Django 2.2.9 on 2020-01-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, unique=True, verbose_name='Label')),
                ('url', models.URLField(blank=True, max_length=256, null=True, verbose_name='Website address')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('components', models.ManyToManyField(related_name='Trainings', to='core.Component', verbose_name='Components')),
                ('training_subdomains', models.ManyToManyField(related_name='Trainings', to='core.TrainingSubdomain', verbose_name='Training subdomains')),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
            },
        ),
    ]
