# Generated by Django 2.2.9 on 2020-01-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_building'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Building'},
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('campus', 'label')},
        ),
    ]
