# Generated by Django 2.2.9 on 2020-01-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200113_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='BachelorMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, unique=True, verbose_name='Label')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Bachelor mention',
                'verbose_name_plural': 'Bachelor mentions',
            },
        ),
    ]
