# Generated by Django 2.2.9 on 2020-01-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_publictype'),
        ('core', '0006_generalbachelorteaching'),
    ]

    operations = [
    ]
