# Generated by Django 2.2.9 on 2020-01-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20200115_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256, unique=True, verbose_name='Label')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('purge_date', models.DateField(verbose_name='Purge date')),
                ('registration_start_date', models.DateField(verbose_name='registration date')),
            ],
            options={
                'verbose_name': 'Univesity year',
                'verbose_name_plural': 'Univesity years',
            },
        ),
        migrations.AlterModelOptions(
            name='generalbachelorteaching',
            options={'verbose_name': 'General bachelor specialty teaching', 'verbose_name_plural': 'General bachelor specialties teachings'},
        ),
    ]
