# Generated by Django 2.2.9 on 2020-01-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200115_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityyear',
            name='purge_date',
            field=models.DateField(null=True, verbose_name='Purge date'),
        ),
        migrations.AlterField(
            model_name='universityyear',
            name='registration_start_date',
            field=models.DateField(verbose_name='Registration date'),
        ),
    ]
