# Generated by Django 2.2.9 on 2020-01-16 16:20

from django.db import migrations, models
import immersionlyceens.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200115_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityyear',
            options={'verbose_name': 'University year', 'verbose_name_plural': 'University years'},
        ),
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('address2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address2')),
                ('address3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address3')),
                ('department', models.CharField(choices=[('01', 'Ain'), ('02', 'Aisne'), ('03', 'Allier'), ('04', 'Alpes-de-Haute-Provence'), ('05', 'Hautes-Alpes'), ('06', 'Alpes-Maritimes'), ('07', 'Ardèche'), ('08', 'Ardennes'), ('09', 'Ariège'), ('10', 'Aube'), ('11', 'Aude'), ('12', 'Aveyron'), ('13', 'Bouches-du-Rhône'), ('14', 'Calvados'), ('15', 'Cantal'), ('16', 'Charente'), ('17', 'Charente-Maritime'), ('18', 'Cher'), ('19', 'Corrèze'), ('21', "Côte-d'Or"), ('22', "Côtes-d'Armor"), ('23', 'Creuse'), ('24', 'Dordogne'), ('25', 'Doubs'), ('26', 'Drôme'), ('27', 'Eure'), ('28', 'Eure-et-Loir'), ('29', 'Finistère'), ('2A', 'Corse-du-Sud'), ('2B', 'Haute-Corse'), ('30', 'Gard'), ('31', 'Haute-Garonne'), ('32', 'Gers'), ('33', 'Gironde'), ('34', 'Hérault'), ('35', 'Ille-et-Vilaine'), ('36', 'Indre'), ('37', 'Indre-et-Loire'), ('38', 'Isère'), ('39', 'Jura'), ('40', 'Landes'), ('41', 'Loir-et-Cher'), ('42', 'Loire'), ('43', 'Haute-Loire'), ('44', 'Loire-Atlantique'), ('45', 'Loiret'), ('46', 'Lot'), ('47', 'Lot-et-Garonne'), ('48', 'Lozère'), ('49', 'Maine-et-Loire'), ('50', 'Manche'), ('51', 'Marne'), ('52', 'Haute-Marne'), ('53', 'Mayenne'), ('54', 'Meurthe-et-Moselle'), ('55', 'Meuse'), ('56', 'Morbihan'), ('57', 'Moselle'), ('58', 'Nièvre'), ('59', 'Nord'), ('60', 'Oise'), ('61', 'Orne'), ('62', 'Pas-de-Calais'), ('63', 'Puy-de-Dôme'), ('64', 'Pyrénées-Atlantiques'), ('65', 'Hautes-Pyrénées'), ('66', 'Pyrénées-Orientales'), ('67', 'Bas-Rhin'), ('68', 'Haut-Rhin'), ('69', 'Rhône'), ('70', 'Haute-Saône'), ('71', 'Saône-et-Loire'), ('72', 'Sarthe'), ('73', 'Savoie'), ('74', 'Haute-Savoie'), ('75', 'Paris'), ('76', 'Seine-Maritime'), ('77', 'Seine-et-Marne'), ('78', 'Yvelines'), ('79', 'Deux-Sèvres'), ('80', 'Somme'), ('81', 'Tarn'), ('82', 'Tarn-et-Garonne'), ('83', 'Var'), ('84', 'Vaucluse'), ('85', 'Vendée'), ('86', 'Vienne'), ('87', 'Haute-Vienne'), ('88', 'Vosges'), ('89', 'Yonne'), ('90', 'Territoire de Belfort'), ('91', 'Essonne'), ('92', 'Hauts-de-Seine'), ('93', 'Seine-Saint-Denis'), ('94', 'Val-de-Marne'), ('95', "Val-d'Oise"), ('971', 'Guadeloupe'), ('972', 'Martinique'), ('973', 'Guyane'), ('974', 'La Réunion'), ('976', 'Mayotte')], max_length=128, verbose_name='Department')),
                ('city', immersionlyceens.fields.UpperCharField(max_length=255, verbose_name='City')),
                ('zip_code', models.CharField(max_length=128, verbose_name='Zip Code')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('head_teacher_name', models.CharField(help_text='civility last name first name', max_length=255, verbose_name='Head teacher name')),
                ('referent_name', models.CharField(help_text='last name first name', max_length=255, verbose_name='Referent name')),
                ('referent_phone_number', models.CharField(max_length=20, verbose_name='Referent phone number')),
                ('referent_email', models.EmailField(max_length=254, verbose_name='Referent email')),
                ('convention_start_date', models.DateField(blank=True, null=True, verbose_name='Convention start date')),
                ('convention_end_date', models.DateField(blank=True, null=True, verbose_name='Convention end date')),
            ],
            options={
                'verbose_name': 'High school',
                'unique_together': {('label', 'city')},
            },
        ),
    ]
