# Generated by Django 2.2.9 on 2020-01-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200115_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256, unique=True, verbose_name='Label')),
                ('year_start_date', models.DateField(null=True)),
                ('year_end_date', models.DateField(null=True)),
                ('year_registration_start_date', models.DateField(null=True)),
                ('year_nb_authorized_immersion', models.IntegerField()),
                ('semester1_start_date', models.DateField(null=True)),
                ('semester1_end_date', models.DateField(null=True)),
                ('semester1_nb_authorized_immersion', models.DateField(null=True)),
                ('semester2_start_date', models.DateField(null=True)),
                ('semester2_end_date', models.DateField(null=True)),
                ('semester2_registration_start_date', models.DateField(null=True)),
                ('registration_start_date_per_semester', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Vacation',
                'verbose_name_plural': 'Vacations',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256, unique=True, verbose_name='Label')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256, unique=True, verbose_name='Label')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Vacation',
                'verbose_name_plural': 'Vacations',
            },
        ),
        migrations.AlterModelOptions(
            name='universityyear',
            options={'verbose_name': 'University year', 'verbose_name_plural': 'University years'},
        ),
    ]
