# Generated by Django 2.2.9 on 2020-01-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200116_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschool',
            name='zip_code',
            field=models.CharField(max_length=128, verbose_name='Zip code'),
        ),
    ]
