# Generated by Django 2.2.9 on 2020-01-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200116_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='calendar_mode',
            field=models.CharField(choices=[('YEAR', 'Year'), ('SEMESTER', 'Semester')], default='YEAR', max_length=16, verbose_name='Calendar mode'),
        ),
    ]
