# Generated by Django 2.2.9 on 2020-01-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200117_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='semester1_nb_authorized_immersion',
            new_name='semester1_registration_start_date',
        ),
    ]
