# Generated by Django 2.2.9 on 2020-01-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200117_1353'),
        ('core', '0013_auto_20200117_0932'),
    ]

    operations = [
    ]
