# Generated by Django 2.2.9 on 2020-01-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20200117_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='global_evaluation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Global evaluation send date'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='registration_start_date_per_semester',
            field=models.PositiveIntegerField(default=2, verbose_name='Number of authorized immersions per semester'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='semester1_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Semester 1 end date'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='semester1_registration_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Semester 1 start registration date'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='semester1_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Semester 1 start date'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='semester2_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Semester 2 end date'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='semester2_registration_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Semester 2 start registration date'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='semester2_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Semester 2 start date'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='year_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Year end date'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='year_nb_authorized_immersion',
            field=models.PositiveIntegerField(default=4, verbose_name='Number of authorized immersions per year'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='year_registration_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Year start registration date'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='year_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Year start date'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
    ]
