# Generated by Django 2.2.9 on 2020-01-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200120_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='immersionuser',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='referents', to='core.Component', verbose_name='Components'),
        ),
    ]
