# Generated by Django 2.2.9 on 2020-01-22 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_immersionuser_components'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('teachers', models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Teachers')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.Training', verbose_name='Training')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'unique_together': {('training', 'label')},
            },
        ),
    ]
