# Generated by Django 2.2.9 on 2020-01-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccompanyingDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('public_type', models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('HIGHSCHOOLSTUDENT', 'High school student')], max_length=128, verbose_name='Public Type')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('document', models.FileField(blank=True, null=True, upload_to='', verbose_name='Document')),
            ],
        ),
    ]
