# Generated by Django 2.2.9 on 2020-01-23 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_accompanyingdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accompanyingdocument',
            name='document',
            field=models.FileField(upload_to='', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='accompanyingdocument',
            name='public_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publictypes', to='core.PublicType'),
        ),
    ]
