# Generated by Django 2.2.9 on 2020-01-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200123_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accompanyingdocument',
            options={'verbose_name': 'Accompanying document', 'verbose_name_plural': 'Accompanying documents'},
        ),
        migrations.AlterModelOptions(
            name='publictype',
            options={'verbose_name': 'Public type', 'verbose_name_plural': 'Public types'},
        ),
        migrations.AlterField(
            model_name='accompanyingdocument',
            name='label',
            field=models.CharField(max_length=255, unique=True, verbose_name='Label'),
        ),
    ]
