# Generated by Django 2.2.9 on 2020-01-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200123_1141'),
        ('core', '0018_informationtext'),
    ]

    operations = [
    ]
