# Generated by Django 2.2.9 on 2020-01-24 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20200124_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True, verbose_name='Label')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('document', models.FileField(upload_to='uploads/publicdocs/%Y', verbose_name='Document')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'Public document',
                'verbose_name_plural': 'Public documents',
            },
        ),
        migrations.AlterField(
            model_name='accompanyingdocument',
            name='document',
            field=models.FileField(upload_to='uploads/accompanyingdocs/%Y', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='accompanyingdocument',
            name='public_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publictypes', to='core.PublicType', verbose_name='Public type'),
        ),
    ]
