# Generated by Django 2.2.9 on 2020-01-24 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20200124_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=128, unique=True, verbose_name='Label')),
                ('description', models.CharField(max_length=512, verbose_name='Description')),
                ('subject', models.CharField(max_length=256, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Body')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.AlterField(
            model_name='accompanyingdocument',
            name='document',
            field=models.FileField(upload_to='uploads/docs/%Y', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='accompanyingdocument',
            name='public_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publictypes', to='core.PublicType', verbose_name='Public type'),
        ),
    ]
