# Generated by Django 2.2.9 on 2020-01-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200124_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplateVars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Code')),
                ('description', models.CharField(max_length=128, unique=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Template variable',
                'verbose_name_plural': 'Template variables',
            },
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='available_vars',
            field=models.ManyToManyField(related_name='mail_templates', to='core.MailTemplateVars', verbose_name='Available variables'),
        ),
    ]
