# Generated by Django 2.2.9 on 2020-01-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200124_1516'),
        ('core', '0022_auto_20200124_1625'),
    ]

    operations = [
    ]
