# Generated by Django 2.2.9 on 2020-01-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_20200127_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailtemplate',
            options={'verbose_name': 'Mail template', 'verbose_name_plural': 'Mail templates'},
        ),
    ]
