# Generated by Django 2.2.9 on 2020-01-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200128_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accompanyingdocument',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='accompanyingdocument',
            name='document',
            field=models.FileField(help_text='Only files with type (doc,pdf,xls,ods,odt)', upload_to='uploads/accompanyingdocs/%Y', verbose_name='Document'),
        ),
        migrations.RemoveField(
            model_name='accompanyingdocument',
            name='public_type',
        ),
        migrations.AddField(
            model_name='accompanyingdocument',
            name='public_type',
            field=models.ManyToManyField(related_name='publictypes', to='core.PublicType', verbose_name='Public type'),
        ),
        migrations.AlterField(
            model_name='informationtext',
            name='code',
            field=models.CharField(help_text='civility last name first name', max_length=64, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='publicdocument',
            name='document',
            field=models.FileField(help_text='Only files with type (doc,pdf,xls,ods,odt)', upload_to='uploads/publicdocs/%Y', verbose_name='Document'),
        ),
    ]
