# Generated by Django 2.2.9 on 2020-01-30 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_attendancecertificatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=16, verbose_name='Room')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='Start time')),
                ('n_places', models.PositiveIntegerField(verbose_name='Number of places')),
                ('additional_information', models.CharField(max_length=128, verbose_name='Additional information')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.Building', verbose_name='Building')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.Campus', verbose_name='Campus')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.Course', verbose_name='Course')),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.CourseType', verbose_name='Course Type')),
                ('teachers', models.ManyToManyField(related_name='slots', to=settings.AUTH_USER_MODEL, verbose_name='Teachers')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.Training', verbose_name='Training')),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
            },
        ),
    ]
