# Generated by Django 2.2.9 on 2020-01-31 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_attendancecertificatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
            ],
            options={
                'verbose_name': 'Evaluation type',
                'verbose_name_plural': 'Evaluation types',
            },
        ),
        migrations.AlterField(
            model_name='accompanyingdocument',
            name='document',
            field=models.FileField(help_text='Only files with type (doc,pdf,xls,ods,odt,docx)', upload_to='uploads/accompanyingdocs/%Y', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='publicdocument',
            name='document',
            field=models.FileField(help_text='Only files with type (doc,pdf,xls,ods,odt,docx)', upload_to='uploads/publicdocs/%Y', verbose_name='Document'),
        ),
        migrations.CreateModel(
            name='EvaluationFormLink',
            fields=[
                ('evaluation_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='evaluationtypes', serialize=False, to='core.EvaluationType', verbose_name='Evaluation type')),
                ('url', models.URLField(blank=True, max_length=256, null=True, verbose_name='Link')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Evaluation form link',
                'verbose_name_plural': 'Evaluation forms links',
            },
        ),
    ]
