# Generated by Django 2.2.9 on 2020-01-30 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_slot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('training', 'course', 'course_type', 'campus', 'building', 'date', 'start_time', 'end_time')},
        ),
    ]
