# Generated by Django 2.2.9 on 2020-01-31 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200130_1512'),
        ('core', '0028_auto_20200131_0855'),
    ]

    operations = [
    ]
