# Generated by Django 2.2.9 on 2020-02-03 13:35

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_merge_20200131_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Website address'),
        ),
    ]
