# Generated by Django 2.2.9 on 2020-01-31 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_merge_20200131_1412'),
        ('core', '0030_merge_20200131_1041'),
    ]

    operations = [
    ]
