# Generated by Django 2.2.9 on 2020-01-31 16:34

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_merge_20200131_1716'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='component',
            managers=[
                ('activated', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='slot',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.CourseType', verbose_name='Course type'),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together=set(),
        ),
    ]
