# Generated by Django 2.2.9 on 2020-02-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200131_1734'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='component',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='informationtext',
            name='description',
            field=models.TextField(default='', max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='informationtext',
            name='content',
            field=models.TextField(max_length=10000, verbose_name='Content'),
        ),
    ]
