# Generated by Django 2.2.9 on 2020-02-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200203_1435'),
        ('core', '0033_auto_20200203_1137'),
    ]

    operations = [
    ]
