# Generated by Django 2.2.9 on 2020-02-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_merge_20200204_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationtext',
            name='code',
            field=models.CharField(max_length=64, verbose_name='Code'),
        ),
    ]
