# Generated by Django 2.2.9 on 2020-02-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200204_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='training',
        ),
        migrations.AlterField(
            model_name='slot',
            name='additional_information',
            field=models.CharField(max_length=128, null=True, verbose_name='Additional information'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(verbose_name='End time'),
        ),
    ]
