# Generated by Django 2.2.9 on 2020-02-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200205_1119'),
        ('core', '0036_auto_20200204_1503'),
    ]

    operations = [
    ]
