# Generated by Django 2.2.9 on 2020-02-10 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_merge_20200207_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accompanyingdocument',
            name='document',
            field=models.FileField(help_text='Seulement des fichiers de type (doc,pdf,xls,ods,odt,docx)', upload_to='uploads/accompanyingdocs/%Y', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='publicdocument',
            name='document',
            field=models.FileField(help_text='Seulement des fichiers de type (doc,pdf,xls,ods,odt,docx)', upload_to='uploads/publicdocs/%Y', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='additional_information',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Additional information'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.Building', verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.Campus', verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='course_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.CourseType', verbose_name='Course type'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='room',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start time'),
        ),
    ]
