# Generated by Django 2.2.9 on 2020-02-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20200210_1443'),
        ('core', '0038_auto_20200210_1522'),
    ]

    operations = [
    ]
