# Generated by Django 2.2.10 on 2020-02-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20200210_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='immersionuser',
            name='validation_string',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='Account validation string'),
        ),
    ]
