# Generated by Django 2.2.9 on 2020-02-12 08:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_merge_20200211_0934'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accompanyingdocument',
            managers=[
                ('activated', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='registration_start_date_per_semester',
            new_name='nb_authorized_immersion_per_semester',
        ),
    ]
