# Generated by Django 2.2.10 on 2020-02-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_immersionuser_destruction_date'),
        ('core', '0040_auto_20200212_0945'),
    ]

    operations = [
    ]
