# Generated by Django 2.2.9 on 2020-02-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20200213_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accompanyingdocument',
            name='document',
            field=models.FileField(help_text='Seulement des fichiers de type (doc,pdf,xls,ods,odt,docx)', upload_to='uploads/accompanyingdocs/%Y', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='publicdocument',
            name='document',
            field=models.FileField(help_text='Seulement des fichiers de type (doc,pdf,xls,ods,odt,docx)', upload_to='uploads/publicdocs/%Y', verbose_name='Document'),
        ),
    ]
