# Generated by Django 2.2.9 on 2020-02-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_immersionuser_recovery_string'),
        ('core', '0044_auto_20200214_1028'),
    ]

    operations = [
    ]
