# Generated by Django 2.2.10 on 2020-02-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_merge_20200218_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Room'),
        ),
    ]
