# Generated by Django 2.2.9 on 2020-02-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20200219_1040'),
        ('core', '0047_auto_20200221_1019'),
    ]

    operations = [
    ]
