# Generated by Django 2.2.11 on 2020-03-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20200312_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highschool',
            name='referent_email',
        ),
        migrations.RemoveField(
            model_name='highschool',
            name='referent_name',
        ),
        migrations.RemoveField(
            model_name='highschool',
            name='referent_phone_number',
        ),
    ]
