# Generated by Django 2.2.11 on 2020-03-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20200320_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='mailing_list',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Mailing list address'),
        ),
    ]
