# Generated by Django 2.2.11 on 2020-03-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_component_mailing_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='immersion',
            name='survey_email_sent',
            field=models.BooleanField(default=False, verbose_name='Survey notification status'),
        ),
    ]
