# Generated by Django 2.2.11 on 2020-03-30 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_immersion_survey_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmersionAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Recipient')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Alert sent status')),
                ('alert_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.Course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Immersion alert',
                'verbose_name_plural': 'Immersion alerts',
                'unique_together': {('email', 'course')},
            },
        ),
    ]
