# Generated by Django 2.2.11 on 2020-03-30 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_immersionalert'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImmersionAlert',
            new_name='UserCourseAlert',
        ),
    ]
