# Generated by Django 2.2.11 on 2020-04-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20200402_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='HigherEducationInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uai_code', models.CharField(max_length=20, unique=True, verbose_name='UAI Code')),
                ('institution_type', models.CharField(max_length=256, verbose_name='Type')),
                ('label', models.CharField(max_length=256, verbose_name='Label')),
                ('acronym', models.CharField(max_length=256, verbose_name='Acronym')),
                ('university', models.CharField(max_length=256, verbose_name='University')),
                ('address', models.CharField(max_length=256, verbose_name='Address')),
                ('zip_code', models.CharField(max_length=5, verbose_name='Zip code')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('academy', models.CharField(max_length=64, verbose_name='Academy')),
                ('area', models.CharField(max_length=64, verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Higher education institution',
                'verbose_name_plural': 'Higher education institutions',
            },
        ),
    ]
