# Generated by Django 2.2.11 on 2020-04-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_highereducationinstitution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highereducationinstitution',
            name='id',
        ),
        migrations.AlterField(
            model_name='highereducationinstitution',
            name='uai_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='UAI Code'),
        ),
    ]
