# Generated by Django 2.2.11 on 2020-04-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20200406_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highereducationinstitution',
            name='academy',
        ),
        migrations.RemoveField(
            model_name='highereducationinstitution',
            name='acronym',
        ),
        migrations.RemoveField(
            model_name='highereducationinstitution',
            name='address',
        ),
        migrations.RemoveField(
            model_name='highereducationinstitution',
            name='area',
        ),
        migrations.RemoveField(
            model_name='highereducationinstitution',
            name='institution_type',
        ),
        migrations.RemoveField(
            model_name='highereducationinstitution',
            name='university',
        ),
        migrations.RemoveField(
            model_name='highereducationinstitution',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='highereducationinstitution',
            name='department',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='highereducationinstitution',
            name='city',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='highereducationinstitution',
            name='label',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Label'),
        ),
    ]
