# Generated by Django 2.2.11 on 2020-04-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20200406_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highereducationinstitution',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='City'),
        ),
    ]
