# Generated by Django 2.2.11 on 2020-04-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20200406_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualStatistics',
            fields=[
                ('year', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Year')),
                ('platform_registrations', models.SmallIntegerField(verbose_name='Platform registrations count')),
                ('one_immersion_registrations', models.SmallIntegerField(verbose_name='Students registered to at least one immersion count')),
                ('multiple_immersions_registrations', models.SmallIntegerField(verbose_name='Students registered to more than one immersion count')),
                ('participants_one_immersion', models.SmallIntegerField(verbose_name='Participants in at least one immersion count')),
                ('participants_multiple_immersions', models.SmallIntegerField(verbose_name='Participants in multiple immersions count')),
                ('immersion_registrations', models.SmallIntegerField(verbose_name='Immersion registrations count')),
                ('seats_count', models.SmallIntegerField(verbose_name='Global seats count')),
                ('components_count', models.SmallIntegerField(verbose_name='Participating components count')),
                ('trainings_one_slot_count', models.SmallIntegerField(verbose_name='Trainings offering at least one slot count')),
                ('courses_one_slot_count', models.SmallIntegerField(verbose_name='Courses offering at least one slot count')),
                ('total_slots_count', models.SmallIntegerField(verbose_name='Total slots count')),
                ('approved_highschools', models.SmallIntegerField(verbose_name='Approved highschools count')),
            ],
        ),
    ]
