# Generated by Django 2.2.11 on 2020-04-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_annualstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualstatistics',
            name='year',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Year label'),
        ),
    ]
