# Generated by Django 2.2.11 on 2020-04-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20200421_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualstatistics',
            name='highschools_without_students',
            field=models.SmallIntegerField(default=0, verbose_name='Highschools with no students'),
        ),
        migrations.AlterField(
            model_name='annualstatistics',
            name='approved_highschools',
            field=models.SmallIntegerField(default=0, verbose_name='Approved highschools count'),
        ),
        migrations.AlterField(
            model_name='annualstatistics',
            name='components_count',
            field=models.SmallIntegerField(default=0, verbose_name='Participating components count'),
        ),
        migrations.AlterField(
            model_name='annualstatistics',
            name='courses_one_slot_count',
            field=models.SmallIntegerField(default=0, verbose_name='Courses offering at least one slot count'),
        ),
        migrations.AlterField(
            model_name='annualstatistics',
            name='immersion_registrations',
            field=models.SmallIntegerField(default=0, verbose_name='Immersion registrations count'),
        ),
        migrations.AlterField(
            model_name='annualstatistics',
            name='multiple_immersions_registrations',
            field=models.SmallIntegerField(default=0, verbose_name='Students registered to more than one immersion count'),
        ),
        migrations.AlterField(
            model_name='annualstatistics',
            name='one_immersion_registrations',
            field=models.SmallIntegerField(default=0, verbose_name='Students registered to at least one immersion count'),
        ),
        migrations.AlterField(
            model_name='annualstatistics',
            name='participants_multiple_immersions',
            field=models.SmallIntegerField(default=0, verbose_name='Participants in multiple immersions count'),
        ),
        migrations.AlterField(
            model_name='annualstatistics',
            name='participants_one_immersion',
            field=models.SmallIntegerField(default=0, verbose_name='Participants in at least one immersion count'),
        ),
        migrations.AlterField(
            model_name='annualstatistics',
            name='platform_registrations',
            field=models.SmallIntegerField(default=0, verbose_name='Platform registrations count'),
        ),
        migrations.AlterField(
            model_name='annualstatistics',
            name='seats_count',
            field=models.SmallIntegerField(default=0, verbose_name='Global seats count'),
        ),
        migrations.AlterField(
            model_name='annualstatistics',
            name='total_slots_count',
            field=models.SmallIntegerField(default=0, verbose_name='Total slots count'),
        ),
        migrations.AlterField(
            model_name='annualstatistics',
            name='trainings_one_slot_count',
            field=models.SmallIntegerField(default=0, verbose_name='Trainings offering at least one slot count'),
        ),
    ]
