# Generated by Django 2.2.11 on 2020-04-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20200421_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='description',
            field=models.CharField(default='', max_length=256, verbose_name='Setting description'),
        ),
    ]
