# Generated by Django 2.2.11 on 2020-04-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_generalsettings_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annualstatistics',
            options={'verbose_name': 'Annual statistics', 'verbose_name_plural': 'Annual statistics'},
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='value',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Setting value'),
        ),
    ]
