# Generated by Django 2.2.10 on 2020-06-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20200427_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bachelormention',
            options={'verbose_name': 'Technological bachelor mention', 'verbose_name_plural': 'Technological bachelor mentions'},
        ),
    ]
