# Generated by Django 3.2 on 2021-09-15 22:47

from django.db import migrations, models
import immersionlyceens.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20210914_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bachelormention',
            options={'verbose_name': 'Technological bachelor series', 'verbose_name_plural': 'Technological bachelor series'},
        ),
        migrations.AlterField(
            model_name='accompanyingdocument',
            name='document',
            field=models.FileField(help_text='Only files with type (doc,pdf,xls,ods,odt,docx)', upload_to='uploads/accompanyingdocs/%Y', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='certificatelogo',
            name='logo',
            field=models.ImageField(help_text='Only files with type (gif, jpg, png)', upload_to='uploads/certificate_logo/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='certificatesignature',
            name='signature',
            field=models.ImageField(help_text='Only files with type (gif, jpg, png)', upload_to='uploads/certificate_signature/', verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='city',
            field=immersionlyceens.fields.UpperCharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='department',
            field=models.CharField(max_length=128, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='zip_code',
            field=models.CharField(max_length=128, verbose_name='Zip code'),
        ),
        migrations.AlterField(
            model_name='publicdocument',
            name='document',
            field=models.FileField(help_text='Only files with type (doc,pdf,xls,ods,odt,docx)', upload_to='uploads/publicdocs/%Y', verbose_name='Document'),
        ),
    ]
