# Generated by Django 3.2.8 on 2021-10-08 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20211005_1333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Component',
            new_name='Structure',
        ),
        migrations.AlterModelOptions(
            name='bachelormention',
            options={'verbose_name': 'Technological bachelor series', 'verbose_name_plural': 'Technological bachelor series'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'verbose_name': 'Structure', 'verbose_name_plural': 'Structures'},
        ),
        migrations.RenameField(
            model_name='annualstatistics',
            old_name='components_count',
            new_name='structures_count'
        ),
        migrations.RenameField(
            model_name='course',
            old_name='component',
            new_name='structure'
        ),
        migrations.RenameField(
            model_name='immersionuser',
            old_name='components',
            new_name='structures'            
        ),
        migrations.RenameField(
            model_name='training',
            old_name='components',
            new_name='structures'
        ),
        migrations.AlterField(
            model_name='accompanyingdocument',
            name='document',
            field=models.FileField(help_text='Only files with type (doc,pdf,xls,ods,odt,docx)', upload_to='uploads/accompanyingdocs/%Y', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='certificatelogo',
            name='logo',
            field=models.ImageField(help_text='Only files with type (gif, jpg, png)', upload_to='uploads/certificate_logo/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='certificatesignature',
            name='signature',
            field=models.ImageField(help_text='Only files with type (gif, jpg, png)', upload_to='uploads/certificate_signature/', verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='publicdocument',
            name='document',
            field=models.FileField(help_text='Only files with type (doc,pdf,xls,ods,odt,docx)', upload_to='uploads/publicdocs/%Y', verbose_name='Document'),
        ),
    ]
