# Generated by Django 3.2.8 on 2021-10-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20211005_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Code')),
                ('establishment_type', models.CharField(choices=[('HIGHER_INST', 'Higher educational institution'), ('HIGH_SCHOOL', 'High school')], max_length=24, verbose_name='Type')),
                ('label', models.CharField(max_length=256, unique=True, verbose_name='Label')),
                ('short_label', models.CharField(max_length=64, unique=True, verbose_name='Short label')),
                ('badge_html_color', models.CharField(max_length=7, verbose_name='Badge color (HTML)')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('master', models.BooleanField(default=True, verbose_name='Master')),
                ('data_source_plugin', models.CharField(max_length=256, unique=True, verbose_name='Accounts source plugin')),
                ('data_source_settings', models.JSONField(blank=True, null=True, verbose_name='Accounts source plugin settings')),
            ],
        ),
    ]
