# Generated by Django 3.2.8 on 2021-10-08 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20211005_1333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Component',
            new_name='Structure',
        ),
        migrations.AlterModelOptions(
            name='bachelormention',
            options={'verbose_name': 'Technological bachelor series', 'verbose_name_plural': 'Technological bachelor series'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'verbose_name': 'Structure', 'verbose_name_plural': 'Structures'},
        ),
        migrations.RemoveField(
            model_name='annualstatistics',
            name='components_count',
        ),
        migrations.RemoveField(
            model_name='course',
            name='component',
        ),
        migrations.RemoveField(
            model_name='immersionuser',
            name='components',
        ),
        migrations.RemoveField(
            model_name='training',
            name='components',
        ),
        migrations.AddField(
            model_name='annualstatistics',
            name='structures_count',
            field=models.SmallIntegerField(default=0, verbose_name='Participating structures count'),
        ),
        migrations.AddField(
            model_name='course',
            name='structure',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.structure', verbose_name='Structure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='immersionuser',
            name='structures',
            field=models.ManyToManyField(blank=True, related_name='referents', to='core.Structure', verbose_name='Structures'),
        ),
        migrations.AddField(
            model_name='training',
            name='structures',
            field=models.ManyToManyField(related_name='Trainings', to='core.Structure', verbose_name='Structures'),
        ),
        migrations.AlterField(
            model_name='accompanyingdocument',
            name='document',
            field=models.FileField(help_text='Only files with type (doc,pdf,xls,ods,odt,docx)', upload_to='uploads/accompanyingdocs/%Y', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='certificatelogo',
            name='logo',
            field=models.ImageField(help_text='Only files with type (gif, jpg, png)', upload_to='uploads/certificate_logo/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='certificatesignature',
            name='signature',
            field=models.ImageField(help_text='Only files with type (gif, jpg, png)', upload_to='uploads/certificate_signature/', verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='publicdocument',
            name='document',
            field=models.FileField(help_text='Only files with type (doc,pdf,xls,ods,odt,docx)', upload_to='uploads/publicdocs/%Y', verbose_name='Document'),
        ),
    ]
