# Generated by Django 3.2.8 on 2021-10-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20211007_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establishment',
            options={'verbose_name': 'Establishment', 'verbose_name_plural': 'Establishments'},
        ),
        migrations.AddField(
            model_name='immersionuser',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.establishment', verbose_name='Establishment'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='data_source_plugin',
            field=models.CharField(blank=True, choices=[('LDAP', 'LDAP')], max_length=256, null=True, verbose_name='Accounts source plugin'),
        ),
    ]
