# Generated by Django 3.2.8 on 2021-10-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20211008_1613'),
        ('core', '0076_auto_20211008_1455'),
    ]

    operations = [
    ]
