# Generated by Django 3.2.8 on 2021-10-13 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_auto_20211011_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='speakers',
            field=models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Speakers'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='speakers',
            field=models.ManyToManyField(related_name='slots', to=settings.AUTH_USER_MODEL, verbose_name='Speakers'),
        ),
    ]
