# Generated by Django 3.2 on 2021-10-12 12:19

from django.db import migrations, models
import immersionlyceens.libs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_auto_20211012_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='parameters',
            field=models.JSONField(default=dict, validators=[immersionlyceens.libs.validators.JsonSchemaValidator('/home/toma/Dev/python/immersionlyceens/immersionlyceens/apps/core/schemas/general_settings.json')], verbose_name='Setting parameters'),
        ),
    ]
