# Generated by Django 3.2.8 on 2021-10-12 15:43

from django.db import migrations, models
import immersionlyceens.libs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_alter_generalsettings_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='parameters',
            field=models.JSONField(default=dict, validators=[immersionlyceens.libs.validators.JsonSchemaValidator('/home/toma/Dev/python/immersionlyceens/immersionlyceens/apps/core/schemas/general_settings.json')], verbose_name='Setting configuration'),
        ),
    ]
