# Generated by Django 3.2.8 on 2021-10-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_alter_generalsettings_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschool',
            name='mailing_list',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Mailing list address'),
        ),
        migrations.AddField(
            model_name='highschool',
            name='postbac_immersion',
            field=models.BooleanField(default=False, verbose_name='Offer post-bachelor immersions'),
        ),
    ]
