# Generated by Django 3.2.8 on 2021-10-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_auto_20211013_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.establishment', verbose_name='Establishment'),
        ),
    ]
