# Generated by Django 3.2.8 on 2021-10-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_structure_establishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='label',
            field=models.CharField(max_length=128, verbose_name='Label'),
        ),
    ]
