# Generated by Django 3.2.8 on 2021-10-14 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_alter_training_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.establishment', verbose_name='Establishment'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Label'),
        ),
    ]
