# Generated by Django 3.2.8 on 2021-10-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_auto_20211014_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immersionuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
