# Generated by Django 3.2.8 on 2021-10-20 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_auto_20211019_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='highschool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highschool_training', to='core.highschool', verbose_name='High school'),
        ),
    ]
