# Generated by Django 3.2.8 on 2021-10-21 07:43

import immersionlyceens.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_auto_20211019_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='address',
            field=models.CharField(default='TODO', max_length=255, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='establishment',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address2'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='address3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address3'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='city',
            field=immersionlyceens.fields.UpperCharField(default='TODO', max_length=255, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='establishment',
            name='department',
            field=models.CharField(default='TODO', max_length=128, verbose_name='Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='establishment',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='phone_number',
            field=models.CharField(default='TODO', max_length=20, verbose_name='Phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='establishment',
            name='zip_code',
            field=models.CharField(default='TODO', max_length=128, verbose_name='Zip code'),
            preserve_default=False,
        ),
    ]
