# Generated by Django 3.2.8 on 2021-10-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_training_highschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='structures',
            field=models.ManyToManyField(blank=True, related_name='Trainings', to='core.Structure', verbose_name='Structures'),
        ),
    ]
