# Generated by Django 3.2.8 on 2021-10-22 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_auto_20211021_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='establishment_type',
        ),
        migrations.AlterField(
            model_name='structure',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures', to='core.establishment', verbose_name='Establishment'),
        ),
    ]
