# Generated by Django 3.2.8 on 2021-10-27 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_auto_20211022_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='highschool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.highschool', verbose_name='High school'),
        ),
        migrations.AlterField(
            model_name='accompanyingdocument',
            name='document',
            field=models.FileField(help_text='Seulement des fichiers de type (doc, pdf, xls, ods, odt, docx). Taille max : 20,0\xa0Mio', upload_to='uploads/accompanyingdocs/%Y', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='course',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.structure', verbose_name='Structure'),
        ),
        migrations.AlterField(
            model_name='publicdocument',
            name='document',
            field=models.FileField(help_text='Seulement des fichiers de type (doc, pdf, xls, ods, odt, docx). Taille max : 20,0\xa0Mio', upload_to='uploads/publicdocs/%Y', verbose_name='Document'),
        ),
    ]
