# Generated by Django 3.2.8 on 2021-10-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_auto_20211027_1202'),
    ]

    operations = [
    ]
