# Generated by Django 3.2.8 on 2021-11-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_alter_training_structures'),
        ('core', '0092_auto_20211029_1451'),
    ]

    operations = [
    ]
