# Generated by Django 3.2.8 on 2021-11-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_merge_20211104_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accompanyingdocument',
            name='document',
            field=models.FileField(help_text='Only files with type (doc, pdf, xls, ods, odt, docx). Max file size : 20,0\xa0Mio', upload_to='uploads/accompanyingdocs/%Y', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='publicdocument',
            name='document',
            field=models.FileField(help_text='Only files with type (doc, pdf, xls, ods, odt, docx). Max file size : 20,0\xa0Mio', upload_to='uploads/publicdocs/%Y', verbose_name='Document'),
        ),
    ]
