# Generated by Django 3.2.8 on 2021-11-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_auto_20211104_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accompanyingdocument',
            name='document',
            field=models.FileField(help_text='Seulement des fichiers de type (doc, pdf, xls, ods, odt, docx). Taille max : 20,0\xa0Mio', upload_to='uploads/accompanyingdocs/%Y', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='publicdocument',
            name='document',
            field=models.FileField(help_text='Seulement des fichiers de type (doc, pdf, xls, ods, odt, docx). Taille max : 20,0\xa0Mio', upload_to='uploads/publicdocs/%Y', verbose_name='Document'),
        ),
    ]
