# Generated by Django 3.2.8 on 2021-11-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_auto_20211104_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highschool',
            options={'ordering': ['city', 'label'], 'verbose_name': 'High school'},
        ),
        migrations.AlterField(
            model_name='accompanyingdocument',
            name='document',
            field=models.FileField(help_text='Only files with type (doc, pdf, xls, ods, odt, docx). Max file size : 20,0\xa0Mio', upload_to='uploads/accompanyingdocs/%Y', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='publicdocument',
            name='document',
            field=models.FileField(help_text='Only files with type (doc, pdf, xls, ods, odt, docx). Max file size : 20,0\xa0Mio', upload_to='uploads/publicdocs/%Y', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='training',
            name='structures',
            field=models.ManyToManyField(blank=True, null=True, related_name='Trainings', to='core.Structure', verbose_name='Structures'),
        ),
    ]
