# Generated by Django 3.2.8 on 2021-11-08 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_auto_20211105_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.visit', verbose_name='Visit'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.course', verbose_name='Course'),
        ),
    ]
