# Generated by Django 3.2.8 on 2021-11-09 07:27

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_auto_20211108_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.visit', verbose_name='Visit'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('establishment', 'structure', 'highschool', 'purpose'), name='unique_visit'),
        ),
    ]
