# Generated by Django 3.2.8 on 2021-11-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_auto_20211109_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offoffereventtype',
            name='full_label',
        ),
        migrations.AlterField(
            model_name='offoffereventtype',
            name='label',
            field=models.CharField(max_length=256, unique=True, verbose_name='Label'),
        ),
    ]
