# Generated by Django 3.2.8 on 2021-11-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_auto_20211109_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='Website address'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='room',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Room'),
        ),
    ]
