# Generated by Django 3.2.8 on 2021-11-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_auto_20211110_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='face_to_face',
            field=models.BooleanField(blank=True, default=True, verbose_name='Face to face'),
        ),
    ]
