# Generated by Django 3.2.8 on 2021-11-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_auto_20211116_1203'),
        ('core', '0101_slot_face_to_face'),
    ]

    operations = [
    ]
