# Generated by Django 3.2.8 on 2021-11-19 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_merge_0100_auto_20211116_1203_0101_slot_face_to_face'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffOfferEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256, verbose_name='Label')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.establishment', verbose_name='Establishment')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.offoffereventtype', verbose_name='Event type')),
                ('highschool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.highschool', verbose_name='High school')),
                ('speakers', models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Speakers')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.structure', verbose_name='Structure')),
            ],
            options={
                'verbose_name': 'Off-offer event',
                'verbose_name_plural': 'Off-offer events',
            },
        ),
        migrations.AddField(
            model_name='slot',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.offofferevent', verbose_name='Off offer event'),
        ),
        migrations.AddConstraint(
            model_name='offofferevent',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('establishment', 'structure', 'highschool', 'label', 'event_type'), name='unique_event'),
        ),
    ]
