# Generated by Django 3.2.8 on 2021-11-19 14:35

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_auto_20211119_1416'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='offofferevent',
            name='unique_event',
        ),
        migrations.AlterField(
            model_name='offofferevent',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.establishment', verbose_name='Establishment'),
        ),
        migrations.AlterField(
            model_name='offofferevent',
            name='highschool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.highschool', verbose_name='High school'),
        ),
        migrations.AddConstraint(
            model_name='offofferevent',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('establishment', 'structure', 'label', 'event_type'), name='unique_establishment_event'),
        ),
        migrations.AddConstraint(
            model_name='offofferevent',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('highschool', 'label', 'event_type'), name='unique_highschool_event'),
        ),
    ]
