# Generated by Django 3.2.8 on 2021-12-01 08:36

from django.db import migrations, models
import immersionlyceens.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_auto_20211119_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accompanyingdocument',
            name='document',
            field=models.FileField(help_text='Seulement des fichiers de type (doc, pdf, xls, ods, odt, docx). Taille max : 20,0\xa0Mio', upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='certificatelogo',
            name='logo',
            field=models.ImageField(help_text='Seulement des fichiers de type (gif, jpg, png)', upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='certificatesignature',
            name='signature',
            field=models.ImageField(help_text='Seulement des fichiers de type (gif, jpg, png)', upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='publicdocument',
            name='document',
            field=models.FileField(help_text='Seulement des fichiers de type (doc, pdf, xls, ods, odt, docx). Taille max : 20,0\xa0Mio', upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Document'),
        ),
    ]
