# Generated by Django 3.2.8 on 2021-11-29 09:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_auto_20211119_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='allowed_establishments',
            field=models.ManyToManyField(related_name='_core_slot_allowed_establishments_+', to='core.Establishment', verbose_name='Allowed establishments'),
        ),
        migrations.AddField(
            model_name='slot',
            name='allowed_highschool_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='slot',
            name='allowed_highschools',
            field=models.ManyToManyField(related_name='_core_slot_allowed_highschools_+', to='core.HighSchool', verbose_name='Allowed high schools'),
        ),
        migrations.AddField(
            model_name='slot',
            name='allowed_post_bachelor_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='slot',
            name='allowed_students_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='slot',
            name='use_restrictions',
            field=models.BooleanField(blank=True, default=False, verbose_name='Use restrictions'),
        ),
    ]
