# Generated by Django 3.2.8 on 2021-11-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_auto_20211129_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='use_restrictions',
        ),
        migrations.AddField(
            model_name='slot',
            name='establishment_restrictions',
            field=models.BooleanField(blank=True, default=False, verbose_name='Use establishments restrictions'),
        ),
        migrations.AddField(
            model_name='slot',
            name='levels_restrictions',
            field=models.BooleanField(blank=True, default=False, verbose_name='Use levels restrictions'),
        ),
    ]
