# Generated by Django 3.2.8 on 2021-11-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_auto_20211129_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='establishment_restrictions',
            new_name='establishments_restrictions',
        ),
    ]
