# Generated by Django 3.2.8 on 2021-11-29 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_rename_establishment_restrictions_slot_establishments_restrictions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='allowed_students_levels',
            new_name='allowed_student_levels',
        ),
    ]
