# Generated by Django 3.2.8 on 2021-11-29 15:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_rename_allowed_students_levels_slot_allowed_student_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='allowed_highschool_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='slot',
            name='allowed_post_bachelor_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='slot',
            name='allowed_student_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
