# Generated by Django 3.2.8 on 2021-12-03 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_auto_20211201_0936'),
        ('core', '0109_auto_20211129_1651'),
    ]

    operations = [
    ]
