# Generated by Django 3.2.8 on 2021-12-13 10:44

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_merge_0105_auto_20211201_0936_0109_auto_20211129_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='allowed_establishments',
            field=models.ManyToManyField(blank=True, related_name='_core_slot_allowed_establishments_+', to='core.Establishment', verbose_name='Allowed establishments'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='allowed_highschool_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='slot',
            name='allowed_highschools',
            field=models.ManyToManyField(blank=True, related_name='_core_slot_allowed_highschools_+', to='core.HighSchool', verbose_name='Allowed high schools'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='allowed_post_bachelor_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='slot',
            name='allowed_student_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='slot',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='slots', to=settings.AUTH_USER_MODEL, verbose_name='Speakers'),
        ),
    ]
