# Generated by Django 3.2.8 on 2021-12-20 17:40

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_auto_20211220_1800'),
    ]

    operations = [
    ]
