# Generated by Django 3.2.8 on 2021-12-20 19:23

from django.db import migrations, models
import django.contrib.postgres.fields

def migrate_field_values(apps, schema_editor):
    Slot = apps.get_model("core", "Slot")

    for slot in Slot.objects.raw('SELECT id, saved_allowed_highschool_levels, saved_allowed_post_bachelor_levels, saved_allowed_student_levels FROM core_slot'):
        for value in slot.saved_allowed_highschool_levels or []:
            slot.allowed_highschool_levels.add(value)

        for value in slot.saved_allowed_post_bachelor_levels or []:
            slot.allowed_post_bachelor_levels.add(value)

        for value in slot.saved_allowed_student_levels or []:
            slot.allowed_student_levels.add(value)


class Migration(migrations.Migration):
    saved_slots_values = None

    dependencies = [
        ('core', '0112_auto_20211220_1840'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE core_slot ADD COLUMN "saved_allowed_highschool_levels" smallint[]'),
        migrations.RunSQL('UPDATE core_slot SET saved_allowed_highschool_levels = allowed_highschool_levels'),
        migrations.RunSQL('ALTER TABLE core_slot ADD COLUMN "saved_allowed_post_bachelor_levels" smallint[]'),
        migrations.RunSQL('UPDATE core_slot SET saved_allowed_post_bachelor_levels = allowed_post_bachelor_levels'),
        migrations.RunSQL('ALTER TABLE core_slot ADD COLUMN "saved_allowed_student_levels" smallint[]'),
        migrations.RunSQL('UPDATE core_slot SET saved_allowed_student_levels = allowed_student_levels'),

        migrations.RemoveField(
            model_name='slot',
            name='allowed_highschool_levels',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='allowed_post_bachelor_levels',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='allowed_student_levels',
        ),

        migrations.AddField(
            model_name='slot',
            name='allowed_highschool_levels',
            field=models.ManyToManyField(blank=True, related_name='_core_slot_allowed_highschool_levels_+', to='core.HighSchoolLevel', verbose_name='Allowed high school levels'),
        ),
        migrations.AddField(
            model_name='slot',
            name='allowed_post_bachelor_levels',
            field=models.ManyToManyField(blank=True, related_name='_core_slot_allowed_post_bachelor_levels_+', to='core.PostBachelorLevel', verbose_name='Allowed post bachelor levels'),
        ),
        migrations.AddField(
            model_name='slot',
            name='allowed_student_levels',
            field=models.ManyToManyField(blank=True, related_name='_core_slot_allowed_student_levels_+', to='core.StudentLevel', verbose_name='Allowed student levels'),
        ),

        migrations.RunPython(migrate_field_values, migrations.RunPython.noop),
        migrations.RunSQL('ALTER TABLE core_slot DROP COLUMN "saved_allowed_highschool_levels"'),
        migrations.RunSQL('ALTER TABLE core_slot DROP COLUMN "saved_allowed_post_bachelor_levels"'),
        migrations.RunSQL('ALTER TABLE core_slot DROP COLUMN "saved_allowed_student_levels"'),
    ]

