# Generated by Django 3.2.8 on 2021-12-20 19:23

from django.db import migrations, models
import django.contrib.postgres.fields

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0113_1_manual_20211220_2023'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE core_slot ADD COLUMN "saved_allowed_student_levels" smallint[]'),
        migrations.RunSQL('UPDATE core_slot SET saved_allowed_student_levels = allowed_student_levels'),
    ]
