# Generated by Django 3.2.8 on 2021-12-22 21:44

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_auto_20211220_2023'),
    ]

    operations = [
    ]
