# Generated by Django 3.2.8 on 2021-12-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_auto_20211222_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoollevel',
            name='is_post_bachelor',
            field=models.BooleanField(default=False, verbose_name='Is a post-bachelor level'),
        ),
    ]
