# Generated by Django 3.2.8 on 2021-12-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_auto_20211222_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highschoollevel',
            name='requires_bachelor_type',
        ),
        migrations.AddField(
            model_name='highschoollevel',
            name='requires_bachelor_speciality',
            field=models.BooleanField(default=False, verbose_name='Requires bachelor speciality'),
        ),
    ]
