# Generated by Django 3.2.8 on 2022-01-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_auto_20220103_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highschoollevel',
            options={'verbose_name': 'High school level', 'verbose_name_plural': 'High school levels'},
        ),
        migrations.AlterModelOptions(
            name='postbachelorlevel',
            options={'verbose_name': 'Post bachelor level', 'verbose_name_plural': 'Post bachelor levels'},
        ),
        migrations.AlterModelOptions(
            name='studentlevel',
            options={'verbose_name': 'Student level', 'verbose_name_plural': 'Student levels'},
        ),
    ]
