# Generated by Django 3.2.8 on 2022-01-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_auto_20211222_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschoollevel',
            name='order',
            field=models.SmallIntegerField(default=None, null=True, verbose_name='Display order'),
        ),
    ]
