# Generated by Django 3.2.8 on 2022-01-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_auto_20220106_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='postbachelorlevel',
            name='order',
            field=models.SmallIntegerField(default=None, null=True, verbose_name='Display order'),
        ),
        migrations.AddField(
            model_name='studentlevel',
            name='order',
            field=models.SmallIntegerField(default=None, null=True, verbose_name='Display order'),
        ),
    ]
