# Generated by Django 3.2.8 on 2022-01-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_auto_20220106_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoollevel',
            name='order',
            field=models.SmallIntegerField(default=None, unique=True, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='postbachelorlevel',
            name='order',
            field=models.SmallIntegerField(default=None, unique=True, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='studentlevel',
            name='order',
            field=models.SmallIntegerField(default=None, unique=True, verbose_name='Display order'),
        ),
    ]
