# Generated by Django 3.2.8 on 2022-01-20 12:51

from django.db import migrations


def forward_func(apps, schema_editor):
    MailTemplateVars = apps.get_model("core", "MailTemplateVars")

    try:
        mtv = MailTemplateVars.objects.get(code="{{ creneau.type }}")
        mtv.code = "{{ creneau.cours.type }}"
        mtv.save()
    except MailTemplateVars.DoesNotExist:
        pass


def reverse_func(apps, schema_editor):
    print('reverse')

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0126_highschool_badge_html_color'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func)
    ]
