# Generated by Django 3.2.8 on 2022-02-01 09:08

from django.db import migrations, models
import functools
import immersionlyceens.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_auto_20220120_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='logo',
            field=models.ImageField(blank=True, help_text='Seulement des fichiers de type (gif, jpg, png)', null=True, upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='signature',
            field=models.ImageField(blank=True, help_text='Seulement des fichiers de type (gif, jpg, png)', null=True, upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Signature'),
        ),
        migrations.AddField(
            model_name='highschool',
            name='logo',
            field=models.ImageField(blank=True, help_text='Seulement des fichiers de type (gif, jpg, png)', null=True, upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='highschool',
            name='signature',
            field=models.ImageField(blank=True, help_text='Seulement des fichiers de type (gif, jpg, png)', null=True, upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='highschoollevel',
            name='order',
            field=models.PositiveSmallIntegerField(default=functools.partial(immersionlyceens.apps.core.models.get_object_default_order, *('HighSchoolLevel',), **{}), null=True, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='postbachelorlevel',
            name='order',
            field=models.PositiveSmallIntegerField(default=functools.partial(immersionlyceens.apps.core.models.get_object_default_order, *('PostBachelorLevel',), **{}), null=True, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='studentlevel',
            name='order',
            field=models.PositiveSmallIntegerField(default=functools.partial(immersionlyceens.apps.core.models.get_object_default_order, *('StudentLevel',), **{}), null=True, verbose_name='Display order'),
        ),
    ]
