# Generated by Django 3.2.8 on 2022-02-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_auto_20220201_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='signed_charter',
            field=models.BooleanField(default=False, verbose_name='Signed charter'),
        ),
    ]
