# Generated by Django 3.2.8 on 2022-01-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_auto_20220106_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highschoollevel',
            options={'ordering': ['order'], 'verbose_name': 'High school level', 'verbose_name_plural': 'High school levels'},
        ),
        migrations.AlterModelOptions(
            name='postbachelorlevel',
            options={'ordering': ['order'], 'verbose_name': 'Post bachelor level', 'verbose_name_plural': 'Post bachelor levels'},
        ),
        migrations.AlterModelOptions(
            name='studentlevel',
            options={'ordering': ['order'], 'verbose_name': 'Student level', 'verbose_name_plural': 'Student levels'},
        ),
        migrations.AlterField(
            model_name='highschoollevel',
            name='order',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='postbachelorlevel',
            name='order',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='studentlevel',
            name='order',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='Display order'),
        ),
    ]
