# Generated by Django 3.2.8 on 2022-02-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_establishment_signed_charter'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschool',
            name='signed_charter',
            field=models.BooleanField(default=False, verbose_name='Signed charter'),
        ),
    ]
