# Generated by Django 3.2.8 on 2022-02-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_highschool_signed_charter'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='mailing_list',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Mailing list'),
        ),
    ]
