# Generated by Django 3.2.8 on 2022-02-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_establishment_mailing_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='certificate_footer',
            field=models.TextField(blank=True, null=True, verbose_name='Certificate footer'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='certificate_header',
            field=models.TextField(blank=True, null=True, verbose_name='Certificate header'),
        ),
        migrations.AddField(
            model_name='highschool',
            name='certificate_footer',
            field=models.TextField(blank=True, null=True, verbose_name='Certificate footer'),
        ),
        migrations.AddField(
            model_name='highschool',
            name='certificate_header',
            field=models.TextField(blank=True, null=True, verbose_name='Certificate header'),
        ),
    ]
