# Generated by Django 3.2.12 on 2022-02-23 10:58

from django.db import migrations, models
import django.db.models.deletion

def set_random_uai(apps, schema_editor):
    HigherEducationInstitution = apps.get_model('core', 'highereducationinstitution')
    Establishment = apps.get_model('core', 'establishment')

    all_hei = HigherEducationInstitution.objects.all()

    # Do not allow migration if we don't have enough HigherEducationInstitution objects
    if Establishment.objects.all().count() > HigherEducationInstitution.objects.all().count():
        raise

    i = 0

    for establishment in Establishment.objects.all():
        establishment.uai_reference = all_hei[i]
        establishment.save()
        i += 1


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_auto_20220211_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highereducationinstitution',
            options={'ordering': ['city', 'label'], 'verbose_name': 'Higher education institution', 'verbose_name_plural': 'Higher education institutions'},
        ),
        migrations.AddField(
            model_name='establishment',
            name='uai_reference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='establishment', to='core.highereducationinstitution', verbose_name='UAI reference'),
        ),
        migrations.RunPython(set_random_uai),
        migrations.AlterField(
            model_name='establishment',
            name='uai_reference',
            field=models.OneToOneField(blank=False, null=False, unique=True, on_delete=django.db.models.deletion.PROTECT, related_name='establishment', to='core.highereducationinstitution', verbose_name='UAI reference'),
        )
    ]
