# Generated by Django 3.2.8 on 2022-02-28 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_auto_20220223_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='uai_reference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='establishment', to='core.highereducationinstitution', verbose_name='UAI reference'),
        ),
    ]
