# Generated by Django 3.2.8 on 2022-03-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_alter_establishment_uai_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='immersionuser',
            name='creation_email_sent',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Creation email sent'),
        ),
    ]
