# Generated by Django 3.2.12 on 2022-03-15 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_immersionusergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immersionusergroup',
            name='immersionusers',
            field=models.ManyToManyField(related_name='usergroup', to=settings.AUTH_USER_MODEL, verbose_name='Group members'),
        ),
        migrations.CreateModel(
            name='PendingUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('validation_string', models.TextField(unique=True, verbose_name='Accounts link validation string')),
                ('immersionuser1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User 1')),
                ('immersionuser2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User 2')),
            ],
            options={
                'verbose_name': 'Pending accounts link',
                'verbose_name_plural': 'Pending accounts link',
                'ordering': ['pk'],
            },
        ),
    ]
