# Generated by Django 3.2.8 on 2022-03-24 08:53

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_highschool_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschool',
            name='country',
            field=django_countries.fields.CountryField(default='FR', max_length=2, verbose_name='Country'),
        ),
    ]
