# Generated by Django 3.2.12 on 2022-05-04 09:16

from django.db import migrations, models
import immersionlyceens.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_alter_highschool_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetype',
            options={'ordering': ['label'], 'verbose_name': 'Course type', 'verbose_name_plural': 'Course types'},
        ),
        migrations.AlterField(
            model_name='accompanyingdocument',
            name='document',
            field=models.FileField(help_text='Seulement des fichiers de type (doc, pdf, xls, ods, odt, docx, xlsx). Taille max : 20,0\xa0Mio', upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='publicdocument',
            name='document',
            field=models.FileField(help_text='Seulement des fichiers de type (doc, pdf, xls, ods, odt, docx, xlsx). Taille max : 20,0\xa0Mio', upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Document'),
        ),
    ]
