# Generated by Django 3.2.12 on 2022-05-04 12:42

from django.db import migrations, models
import immersionlyceens.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_auto_20220504_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmersupFile',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='File code')),
                ('file', models.FileField(upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='File')),
            ],
            options={
                'verbose_name': 'Logo for attendance certificate',
                'verbose_name_plural': 'Logo for attendance certificate',
            },
        ),
    ]
