# Generated by Django 3.2.12 on 2022-05-17 13:06

from django.db import migrations, models
import immersionlyceens.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_immersupfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='immersupfile',
            options={'verbose_name': 'ImmerSup file', 'verbose_name_plural': 'ImmerSup files'},
        ),
        migrations.AddField(
            model_name='annualstatistics',
            name='immersion_participation_ratio',
            field=models.FloatField(default=0, verbose_name='Course immersions participations ratio'),
        ),
        migrations.AddField(
            model_name='annualstatistics',
            name='immersion_participations',
            field=models.SmallIntegerField(default=0, verbose_name='Course immersions participations count'),
        ),
        migrations.AddField(
            model_name='annualstatistics',
            name='no_course_immersions_registrations',
            field=models.SmallIntegerField(default=0, verbose_name='Students without any course immersion registration'),
        ),
        migrations.AlterField(
            model_name='annualstatistics',
            name='immersion_registrations',
            field=models.SmallIntegerField(default=0, verbose_name='Course immersions registrations count'),
        ),
        migrations.AlterField(
            model_name='annualstatistics',
            name='multiple_immersions_registrations',
            field=models.SmallIntegerField(default=0, verbose_name='Students registered to more than one course immersion count'),
        ),
        migrations.AlterField(
            model_name='annualstatistics',
            name='one_immersion_registrations',
            field=models.SmallIntegerField(default=0, verbose_name='Students registered to at least one course immersion count'),
        ),
        migrations.AlterField(
            model_name='immersupfile',
            name='file',
            field=models.FileField(help_text='Seulement des fichiers de type (doc, pdf, xls, ods, odt, docx, xlsx). Taille max : 20,0\xa0Mio', upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='File'),
        ),
    ]
