# Generated by Django 3.2.12 on 2022-05-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_auto_20220517_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualstatistics',
            name='active_courses_count',
            field=models.SmallIntegerField(default=0, verbose_name='Active courses count'),
        ),
        migrations.AddField(
            model_name='annualstatistics',
            name='active_trainings_count',
            field=models.SmallIntegerField(default=0, verbose_name='Active trainings count'),
        ),
    ]
