# Generated by Django 3.2.8 on 2022-06-10 13:00

from django.db import migrations, models
import immersionlyceens.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_auto_20220519_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomThemeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('JS', 'Js'), ('CSS', 'Css'), ('IMG', 'Image'), ('FAVICON', 'Favicon')], default='CSS', max_length=7, verbose_name='File type')),
                ('file', models.FileField(help_text='Seulement des fichiers de type (png, jpeg, jpg, ico, css, js). Taille max : 20,0\xa0Mio', upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='File')),
            ],
            options={
                'verbose_name': 'Custom theme file',
                'verbose_name_plural': 'Custom theme files',
            },
        ),
    ]
