# Generated by Django 3.2.15 on 2023-01-04 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_customthemefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Speakers'),
        ),
        migrations.AddConstraint(
            model_name='training',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('highschool', 'label'), name='unique_highschool_training'),
        ),
    ]
