# Generated by Django 3.2.16 on 2023-02-10 09:20

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_auto_20230111_1401'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('label', 'establishment'), name='unique_campus'),
        ),
    ]
