# Generated by Django 3.2.16 on 2023-02-10 10:59

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_campus_unique_campus'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='building',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('label', 'campus'), name='unique_building'),
        ),
    ]
