# Generated by Django 3.2.16 on 2023-02-10 15:59

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_auto_20230210_1159'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='highschool',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='highschool',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('label', 'city'), name='unique_highschool'),
        ),
    ]
