# Generated by Django 3.2.16 on 2023-03-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_alter_slot_n_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='cancellation_limit_delay',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Cancellation limit delay'),
        ),
        migrations.AddField(
            model_name='slot',
            name='registration_limit_delay',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Registration limit delay'),
        ),
    ]
