# Generated by Django 3.2.16 on 2023-03-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_auto_20230316_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='cancellation_limit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancellation limit'),
        ),
        migrations.AddField(
            model_name='slot',
            name='registration_limit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Registration limit'),
        ),
    ]
