# Generated by Django 3.2.16 on 2023-03-20 15:17

from django.db import migrations, models
import functools
import immersionlyceens.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_auto_20230317_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('order', models.PositiveSmallIntegerField(default=functools.partial(immersionlyceens.apps.core.models.get_object_default_order, *('FaqEntry',), **{}), null=True, verbose_name='Display order')),
                ('question', models.TextField(max_length=2000, verbose_name='Question')),
                ('answer', models.TextField(max_length=10000, verbose_name='Answer')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Faq entry',
                'verbose_name_plural': 'Faq entries',
            },
        ),
    ]
