# Generated by Django 3.2.16 on 2023-03-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_auto_20230317_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256, unique=True, verbose_name='Label')),
                ('registration_start_date', models.DateField(verbose_name='Registrations start date')),
                ('immersion_start_date', models.DateField(verbose_name='Immersions start date')),
                ('immersion_end_date', models.DateField(verbose_name='Immersions end date')),
                ('allowed_immersions', models.PositiveIntegerField(default=1, verbose_name='Allowed immersions per student')),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'ordering': ['registration_start_date'],
            },
        ),
    ]
