# Generated by Django 3.2.16 on 2023-03-20 15:17

import functools

from django.db import migrations, models

from immersionlyceens.apps.core.models import InformationText


def population_information_text(apps, schema_editor):
    codes = ['INTRO_OFFER_COURSE', 'INTRO_CONTACT', 'INTRO_FAQ']


    texts = InformationText.objects.all()

    if not texts.filter(code='INTRO_CONTACT').exists():
        InformationText.objects.create(
                label = "Texte d'introduction pour le formulaire de contact",
                code = "INTRO_CONTACT",
                content = "<p>Vous pouvez nous contacter via ce formulaire, nous vous répondrons dans les plus brefs délais.</p>",
                description = "Texte d'introduction en haut du formulaire de contact",
                active = False,
        )

    if not texts.filter(code='INTRO_OFFER_COURSE').exists():
        InformationText.objects.create(
                label = "Texte d'introduction sur l'offre de cours",
                code = "INTRO_OFFER_COURSE",
                content = "<p>Vous pouvez retrouver ici l'ensemble des cours ouverts à l'immersion, cela vous permettra de participer à des cours avec des étudiants.</p>",
                description = "Texte d'intro sur l'offre de cours (page offre de cours)",
                active = False,
        )

    if not texts.filter(code='INTRO_FAQ').exists():
        InformationText.objects.create(
                label = "Texte d'intro de la page FAQ",
                code = "INTRO_FAQ",
                content = "<p>Nous avons rassemblé les questions les plus fréquemment posées pour vous donnez plus d'informations.</p>",
                description = "Texte d'intro sur la foire aux questions (page FAQ)",
                active = False,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_faqentry'),
    ]

    operations = [
      migrations.RunPython(population_information_text),
    ]
