# Generated by Django 3.2.18 on 2023-03-23 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_period'),
        ('core', '0155_add_information_texts'),
    ]

    operations = [
    ]
