# Generated by Django 3.2.18 on 2023-03-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_merge_0154_period_0155_add_information_texts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatelogo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='faqentry',
            options={'ordering': ['order'], 'verbose_name': 'Faq entry', 'verbose_name_plural': 'Faq entries'},
        ),
    ]
