# Generated by Django 3.2.18 on 2023-03-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_auto_20230330_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschool',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
