# Generated by Django 3.2.18 on 2023-03-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_highschool_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschool',
            name='with_convention',
            field=models.BooleanField(default=True, verbose_name='Has a convention'),
        ),
    ]
