# Generated by Django 3.2.18 on 2023-04-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_highschool_with_convention'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['immersion_start_date'], 'verbose_name': 'Period', 'verbose_name_plural': 'Periods'},
        ),
    ]
