# Generated by Django 3.2.18 on 2023-04-12 09:11

from django.db import migrations, models
import functools
import immersionlyceens.apps.core.models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_add_cons_str_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Label')),
                ('label', models.CharField(max_length=128, unique=True, verbose_name='Label')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='AttestationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True, verbose_name='Label')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveSmallIntegerField(default=functools.partial(immersionlyceens.apps.core.models.get_object_default_order, *('AttestationDocument',), **{}), null=True, unique=True, verbose_name='Order')),
                ('for_minors', models.BooleanField(default=True, verbose_name='For minors')),
                ('mandatory', models.BooleanField(default=True, verbose_name='Mandatory')),
                ('requires_validity_date', models.BooleanField(default=True, verbose_name='Requires a validity date')),
                ('template', models.FileField(help_text='Seulement des fichiers de type (doc, pdf, xls, ods, odt, docx, xlsx). Taille max : 20,0\xa0Mio', upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Template')),
                ('profiles', models.ManyToManyField(blank=True, limit_choices_to={'code__in': ['LYC_W_CONV', 'LYC_WO_CONV', 'VISITOR']}, related_name='attestations', to='core.Profile', verbose_name='Profiles')),
            ],
            options={
                'verbose_name': 'Attestation document',
                'verbose_name_plural': 'Attestation documents',
                'ordering': ['order'],
            },
        ),
    ]
