# Generated by Django 3.2.18 on 2023-04-13 12:04
from datetime import datetime

from django.db import migrations, models
from django.utils.timezone import get_current_timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_add_attestation_document_deposit_delay_general_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='immersion',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Registration date'),
        ),
        migrations.AddField(
            model_name='immersion',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now(tz=get_current_timezone()), verbose_name='Registration date'),
            preserve_default=False,
        ),
    ]
