# Generated by Django 3.2.18 on 2023-04-13 08:50

from django.db import migrations


def add_default_profiles(apps, schema_editor):

    Profile = apps.get_model('core', 'Profile')

    profiles = {
        'LYC_W_CONV': {
            "code": "LYC_W_CONV",
            "label": "Lycéen(ne) d'un lycée conventionné",
            "active": True
        },
        'LYC_WO_CONV': {
            "code": "LYC_WO_CONV",
            "label": "Lycéen(ne) d'un lycée non conventionné",
            "active": True
        },
        'VIS': {
            "code": "VIS",
            "label": "Visiteur",
            "active": True
        },
    }

    for code, data in profiles.items():
        if not Profile.objects.filter(code=code).exists():
            Profile.objects.create(**data)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_attestationdocument_profile'),
    ]

    operations = [
        migrations.RunPython(add_default_profiles),
    ]
