# Generated by Django 3.2.18 on 2023-04-13 14:28

from django.db import migrations, models
import functools
import immersionlyceens.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_auto_20230413_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationdocument',
            name='order',
            field=models.PositiveSmallIntegerField(default=functools.partial(immersionlyceens.apps.core.models.get_object_default_order, *('AttestationDocument',), **{}), null=True, unique=True, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='attestationdocument',
            name='profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to={'code__in': ['LYC_W_CONV', 'LYC_WO_CONV', 'VIS']}, related_name='attestations', to='core.Profile', verbose_name='Profiles'),
        ),
        migrations.AlterField(
            model_name='attestationdocument',
            name='template',
            field=models.FileField(blank=True, help_text='Seulement des fichiers de type (doc, pdf, xls, ods, odt, docx, xlsx). Taille max : 20,0\xa0Mio', null=True, upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code'),
        ),
    ]
