# Generated by Django 3.2.18 on 2023-04-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_alter_immersion_cancellation_date'),
        ('core', '0166_auto_20230413_1628'),
    ]

    operations = [
    ]
