# Generated by Django 3.2.18 on 2023-04-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_merge_20230419_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='additional_information',
            field=models.TextField(blank=True, null=True, verbose_name='Additional information'),
        ),
    ]
