# Generated by Django 3.2.18 on 2023-05-04 13:25

from django.db import migrations

def create_template(apps, schema_editor):
    MailTemplateVars = apps.get_model('core', 'MailTemplateVars')
    MailTemplate = apps.get_model('core', 'MailTemplate')

    template_var_data = {
        "code": "{{ justificatifs_expires }}",
        "description": "Liste des justificatifs à renouveler lorsque la fin de validité approche"
    }

    MailTemplateVars.objects.create(**template_var_data)

    template_data = {
        "code": "CPT_DEPOT_PIECE",
        "label": "Mail envoyé lorsqu'un justificatif doit être renvoyé",
        "description": """L'envoi du mail se base sur la date de validité des justificatifs """
                       """et sur le paramètre 'ATTESTATION_DOCUMENT_DEPOSIT_DELAY'""",
        "subject": "Fin de validité d'un ou plusieurs justificatifs",
        "body": """<p>Bonjour,</p><p>Votre fiche comporte un ou plusieurs justificatifs arrivant à expiration :<br></p>"""
                """<p>{{ justificatifs_expires }}<br></p>"""
                """<p>Merci de le ou les renouveler avant la date limite afin de faire revalider votre fiche.<br></p>"""
                """<p>Cordialement, </p><p>Le service en ligne d'immersions</p>""",
        "active": True
    }

    MailTemplate.objects.create(**template_data)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_alter_slot_additional_information'),
    ]

    operations = [
        migrations.RunPython(create_template),
    ]
