# Generated by Django 3.2.18 on 2023-05-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_new_template_CPT_DEPOT_PIECE__20230504_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='BachelorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, unique=True, verbose_name='Label')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('pre_bachelor_level', models.BooleanField(default=False, verbose_name='Is pre-bachelor level')),
            ],
            options={
                'verbose_name': 'Bachelor type',
                'verbose_name_plural': 'Bachelor types',
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='slot',
            name='allowed_bachelor_types',
            field=models.ManyToManyField(blank=True, related_name='_core_slot_allowed_bachelor_types_+', to='core.BachelorMention', verbose_name='Allowed high school levels'),
        ),
        migrations.AddField(
            model_name='slot',
            name='bachelors_restrictions',
            field=models.BooleanField(blank=True, default=False, verbose_name='Use bachelors restrictions'),
        ),
    ]
