# Generated by Django 3.2.18 on 2023-05-09 07:42

from django.db import migrations

def create_bachelor_types(apps, schema_editor):
    BachelorType = apps.get_model('core', 'BachelorType')

    bachelor_types = [{
        "label": "Général",
        "active": True,
        "pre_bachelor_level": True
    }, {
        "label": "Technologique",
        "active": True,
        "pre_bachelor_level": True
    }, {
        "label": "Professionnel",
        "active": True,
        "pre_bachelor_level": True
    },{
        "label": "DAEU",
        "active": True,
        "pre_bachelor_level": False
    }]


    for bt in bachelor_types:
        BachelorType.objects.create(**bt)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_auto_20230509_0941'),
    ]

    operations = [
        migrations.RunPython(create_bachelor_types),
    ]
