# Generated by Django 3.2.18 on 2023-05-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_auto_20230509_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='allowed_bachelor_series',
            field=models.ManyToManyField(blank=True, related_name='_core_slot_allowed_bachelor_series_+', to='core.BachelorMention', verbose_name='Allowed bachelor mentions'),
        ),
        migrations.AddField(
            model_name='slot',
            name='allowed_bachelor_teachings',
            field=models.ManyToManyField(blank=True, related_name='_core_slot_allowed_bachelor_teachings_+', to='core.GeneralBachelorTeaching', verbose_name='Allowed bachelor teachings'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='allowed_bachelor_types',
            field=models.ManyToManyField(blank=True, related_name='_core_slot_allowed_bachelor_types_+', to='core.BachelorType', verbose_name='Allowed bachelor types'),
        ),
    ]
