# Generated by Django 3.2.18 on 2023-05-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_auto_20230509_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='bachelortype',
            name='general',
            field=models.BooleanField(default=False, verbose_name='Is general type'),
        ),
        migrations.AddField(
            model_name='bachelortype',
            name='professional',
            field=models.BooleanField(default=False, verbose_name='Is professional type'),
        ),
        migrations.AddField(
            model_name='bachelortype',
            name='technological',
            field=models.BooleanField(default=False, verbose_name='Is technological type'),
        ),
    ]
