# Generated by Django 3.2.18 on 2023-05-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0173_auto_20230509_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='allowed_bachelor_series',
        ),
        migrations.AddField(
            model_name='slot',
            name='allowed_bachelor_mentions',
            field=models.ManyToManyField(blank=True, related_name='_core_slot_allowed_bachelor_mentions_+', to='core.BachelorMention', verbose_name='Allowed bachelor mentions'),
        ),
    ]
