# Generated by Django 3.2.18 on 2023-05-11 15:44

from django.db import migrations

def add_training_quota_settings(apps, schema_editor):
    GeneralSettings = apps.get_model('core', "GeneralSettings")

    code = 'ACTIVATE_TRAINING_QUOTAS'

    if not GeneralSettings.objects.filter(setting=code).exists():
        GeneralSettings.objects.create(
            setting=code,
            parameters={
                "type": "object",
                "value": {
                    "activate": False,
                    "default_quota": 2
                },
                "description": "Appliquer des quotas d'immersions en fonction des formations liées aux créneaux"
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_auto_20230510_1219'),
    ]

    operations = [
      migrations.RunPython(add_training_quota_settings),
    ]