# Generated by Django 3.2.18 on 2023-05-12 11:19

from django.db import migrations

def update_bachelor_types(apps, schema_editor):
    BachelorType = apps.get_model('core', 'BachelorType')

    BachelorType.objects.filter(label="Général").update(general=True)
    BachelorType.objects.filter(label="Technologique").update(technological=True)
    BachelorType.objects.filter(label="Professionnel").update(professional=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_add_training_quota_settings'),
    ]

    operations = [
        migrations.RunPython(update_bachelor_types),
    ]
