# Generated by Django 3.2.18 on 2023-05-17 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_auto_20230512_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationdocument',
            name='for_minors',
            field=models.BooleanField(default=True, verbose_name='Attestation reserved for minors'),
        ),
        migrations.CreateModel(
            name='RefStructuresNotificationsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structures', models.ManyToManyField(blank=True, related_name='_core_refstructuresnotificationssettings_structures_+', to='core.Structure', verbose_name='Structures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ref_structure_notifications_settings', to=settings.AUTH_USER_MODEL, verbose_name='Structure Manager')),
            ],
        ),
    ]
