# Generated by Django 3.2.18 on 2023-05-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_auto_20230512_1319'),
    ]

    operations = [
    ]

