# Generated by Django 3.2.18 on 2023-05-24 11:33

from django.db import migrations

def add_training_quota_settings(apps, schema_editor):
    GeneralSettings = apps.get_model('core', "GeneralSettings")

    code = 'AUTO_SLOT_UNSUBSCRIBE_DELAY'

    if not GeneralSettings.objects.filter(setting=code).exists():
        GeneralSettings.objects.create(
            setting=code,
            parameters={
                "type": "integer",
                "value": 15,
                "description": """Si un justificatif expire un jour J, les inscriptions aux créneaux dans """
                               """le délai J+<valeur> seront annulées"""
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0177_new_template_CPT_AVALIDER_REF_ETAB_20230524_0752'),
    ]

    operations = [
      migrations.RunPython(add_training_quota_settings),
    ]


