# Generated by Django 3.2.18 on 2023-05-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0178_add_unsubscribe_delay_setting_20230524_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='canceltype',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='canceltype',
            name='system',
            field=models.BooleanField(default=False, verbose_name='System reserved'),
        ),
        migrations.AlterField(
            model_name='attestationdocument',
            name='for_minors',
            field=models.BooleanField(default=True, verbose_name='Attestation reserved for minors'),
        ),
        migrations.AlterField(
            model_name='immersion',
            name='cancellation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='immersions', to='core.canceltype', verbose_name='Cancellation type'),
        ),
    ]
