# Generated by Django 3.2.16 on 2023-01-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0180_add_system_cancel_type_20230526_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(max_length=128, unique=True, verbose_name='Django command name')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('time', models.TimeField(verbose_name='Execution time')),
                ('monday', models.BooleanField(blank=True, default=False, null=True, verbose_name='Monday')),
                ('tuesday', models.BooleanField(blank=True, default=False, null=True, verbose_name='Tuesday')),
                ('wednesday', models.BooleanField(blank=True, default=False, null=True, verbose_name='Wednesday')),
                ('thursday', models.BooleanField(blank=True, default=False, null=True, verbose_name='Thursday')),
                ('friday', models.BooleanField(blank=True, default=False, null=True, verbose_name='Friday')),
                ('saturday', models.BooleanField(blank=True, default=False, null=True, verbose_name='Saturday')),
                ('sunday', models.BooleanField(blank=True, default=False, null=True, verbose_name='Sunday')),
            ],
            options={
                'verbose_name': 'Scheduled task',
                'verbose_name_plural': 'Scheduled tasks',
                'ordering': ['command_name'],
            },
        ),
    ]
