# Generated by Django 3.2.18 on 2023-05-17 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0180_add_system_cancel_type_20230526_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefStructuresNotificationsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structures', models.ManyToManyField(blank=True, related_name='_core_refstructuresnotificationssettings_structures_+', to='core.Structure', verbose_name='Structures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ref_structure_notifications_settings', to=settings.AUTH_USER_MODEL, verbose_name='Structure Manager')),
            ],
        ),
    ]
