# Generated by Django 3.2.18 on 2023-05-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_scheduledtask_20230530_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='friday',
            field=models.BooleanField(blank=True, default=False, verbose_name='Friday'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='monday',
            field=models.BooleanField(blank=True, default=False, verbose_name='Monday'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='saturday',
            field=models.BooleanField(blank=True, default=False, verbose_name='Saturday'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='sunday',
            field=models.BooleanField(blank=True, default=False, verbose_name='Sunday'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='thursday',
            field=models.BooleanField(blank=True, default=False, verbose_name='Thursday'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='tuesday',
            field=models.BooleanField(blank=True, default=False, verbose_name='Tuesday'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='wednesday',
            field=models.BooleanField(blank=True, default=False, verbose_name='Wednesday'),
        ),
    ]
