# Generated by Django 3.2.18 on 2023-05-30 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0182_auto_20230530_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('success', models.BooleanField(blank=True, default=True, null=True, verbose_name='Success')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.scheduledtask', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Scheduled task log',
                'verbose_name_plural': 'Scheduled task logs',
                'ordering': ['-execution_date'],
            },
        ),
    ]
