# Generated by Django 3.2.18 on 2023-05-04 13:25

from django.db import migrations


def create_template(apps, schema_editor):
    MailTemplateVars = apps.get_model('core', 'MailTemplateVars')
    MailTemplate = apps.get_model('core', 'MailTemplate')

    template_data = {
        "code": "IMMERSION_RAPPEL_STR",
        "label": "Mail de rappel de participation à un créneau pour les refs structures",
        "description": """Mail envoyé à un ref structure n jours avant le créneau."""
                       """Le mail sera envoyé uniquement aux référents Structures qui auront accepté l'envoi dans les paramètres.""",
        "subject": "Rappel : le cours de votre structure en immersion",
        "body": """<p></p><p>Bonjour {{ prenom }} {{ nom }}, </p>"""
                """<p>Vous avez paramétré de recevoir les notifications pour le {% if creneau.estuncours %}le cours{% elif creneau.estunevisite %}la visite au {{ creneau.lycee }}{% elif creneau.estunevenement %}l' évènement{% endif %} organisé par {% if creneau.lycee %}le lycée {{ creneau.lycee }}{% else %}l'établissement {{ creneau.etablissement }}{% if creneau.structure %} - {{ creneau.structure }}{% endif %}{% endif %}.<br></p>{% if creneau.estuncours %}Formation : {{ creneau.cours.formation }}<br>Cours : {{ creneau.cours.libelle }}<br>Type : {{ creneau.cours.type }}<br>{% elif creneau.estunevisite %}Objet de la visite&nbsp; : {{ creneau.visite.libelle }}.<br>{% elif creneau.estunevenement %}Type d'évènement : {{ creneau.evenement.type }}<br>Intitulé : {{ creneau.evenement.libelle }}<br>Description : {{ creneau.evenement.description }}{% endif %}<br><br>Ce créneau aura lieu le {{ creneau.date }} de {{ creneau.heuredebut }} à {{ creneau.heurefin }}.<br><br>{% if creneau.temoindistanciel %}Il aura lieu en distanciel sur le lien suivant : {{ creneau.lien }}{% else %}<br>{% if creneau.campus %}Campus : {{ creneau.campus }}{% endif %}<br>{% if creneau.batiment.libelle %}Bâtiment : {{ creneau.batiment.libelle }}{% endif %}<br>Lieu : {{ creneau.salle }}{% endif %}<br><br>Intervenants :<br>{{ creneau.intervenants }}<br>{% if creneau.info %} Informations complémentaires : {{ creneau.info }}{% endif %}<p>Voici la liste des inscrits : <br>{{ creneau.listeInscrits }}</p>"""
                """<p>Cordialement, </p><p>Le service en ligne d'immersions</p>""",
        "active": True
    }
    if not MailTemplate.objects.filter(code="IMMERSION_RAPPEL_STR").exists():
        template = MailTemplate.objects.create(**template_data)

    # Add these existing vars to the new template
    codes = [
        "{{ nom }}", "{{ prenom }}", "{{ creneau.estuncours }}", "{{ creneau.estunevisite }}",
        "{{ creneau.estunevisite }}", "{{ creneau.lycee }}", "{{ creneau.estunevenement }}", "{{ creneau.lycee }}",
        "{{ creneau.etablissement }}", "{{ creneau.structure }}", "{{ creneau.estuncours }}",
        "{{ creneau.cours.formation }}", "{{ creneau.cours.libelle }}", "{{ creneau.cours.type }}",
        "{{ creneau.estunevisite }}", "{{ creneau.visite.libelle }}", "{{ creneau.estunevenement }}",
        "{{ creneau.evenement.type }}", "{{ creneau.evenement.libelle }}", "{{ creneau.evenement.description }}",
        "{{ creneau.date }}", "{{ creneau.heuredebut }}", "{{ creneau.heurefin }}", "{{ creneau.temoindistanciel }}",
        "{{ creneau.lien }}", "{{ creneau.campus }}", "{{ creneau.batiment.libelle }}", "{{ creneau.salle }}",
        "{{ creneau.intervenants }}", "{{ creneau.info }}", "{{ creneau.listeInscrits }}"
    ]

    for code in codes:
        try:
            template_var = MailTemplateVars.objects.get(code=code)
            template.available_vars.add(template_var)
        except MailTemplateVars.DoesNotExist:
            print(f"Mail template var '{code}' not found")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0182_alter_refstructuresnotificationssettings_structures'),
    ]

    operations = [
        migrations.RunPython(create_template),
    ]

