# Generated by Django 3.2.18 on 2023-06-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0183_scheduledtasklog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledtask',
            options={'verbose_name': 'Scheduled task', 'verbose_name_plural': 'Scheduled tasks'},
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='frequency',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Frequency (in minutes)'),
        ),
    ]
