# Generated by Django 3.2.18 on 2023-06-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0184_auto_20230601_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Execution Date'),
        ),
    ]
