# Generated by Django 3.2.18 on 2023-06-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0182_alter_refstructuresnotificationssettings_structures'),
        ('core', '0185_scheduledtask_date'),
    ]

    operations = [
    ]
