# Generated by Django 3.2.19 on 2023-06-06 12:12

from django.db import migrations, models
import immersionlyceens.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0186_merge_20230602_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='city',
            field=immersionlyceens.fields.UpperCharField(default='', max_length=255, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campus',
            name='zip_code',
            field=models.CharField(default='', max_length=128, verbose_name='Zip code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='frequency',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Frequency (in hours)'),
        ),
    ]
