# Generated by Django 3.2.19 on 2023-06-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0189_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'History', 'verbose_name_plural': 'History'},
        ),
        migrations.AddField(
            model_name='history',
            name='hijacked',
            field=models.CharField(max_length=256, null=True, verbose_name='Hijacked user'),
        ),
        migrations.AlterField(
            model_name='history',
            name='first_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='history',
            name='last_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='history',
            name='username',
            field=models.CharField(max_length=256, null=True, verbose_name='Username'),
        ),
    ]
