# Generated by Django 3.2.19 on 2023-06-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0190_auto_20230607_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='history',
            name='last_name',
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.CharField(max_length=256, null=True, verbose_name='User'),
        ),
    ]
