# Not generated by Django 3.2.19 on 2023-06-09 08:18

from django.db import migrations


def add_highschools_information_texts(apps, schema_editor):
    InformationText = apps.get_model('core', "InformationText")

    if not InformationText.objects.filter(code="INTRO_LYCEES_CONVENTIONNES").exists():
        InformationText.objects.create(
            label="Texte d'introduction sur les lycées conventionnés",
            code="INTRO_LYCEES_CONVENTIONNES",
            content="Si votre lycée fait partie de cette liste, les immersions vous sont ouvertes.",
            description="Texte d'introduction sur les lycées conventionnés sur la partie publique / procédure / Liste des lycées",
            active=False,
        )

    if not InformationText.objects.filter(code="INTRO_LYCEES_NON_CONVENTIONNES").exists():
        InformationText.objects.create(
            label="Texte d'introduction sur les lycées non conventionnés",
            code="INTRO_LYCEES_NON_CONVENTIONNES",
            content="Lorem Elsass Ipsum mitt picon bière munster du ftomi! Ponchour bisame. Flammekueche knèkes rossbolla schneck choucroute un schwanz geburtstàg, Gal!",
            description="Texte d'introduction sur les lycées non conventionnés sur la partie publique / procédure / Liste des lycées",
            active=False,
        )




class Migration(migrations.Migration):

    dependencies = [
        ('core', '0192_remove_universityyear_global_evaluation_date'),
    ]

    operations = [
      migrations.RunPython(add_highschools_information_texts),
    ]

