# Generated by Django 3.2.19 on 2023-07-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0195_training_allowed_immersions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImmersupFile',
        ),
        migrations.AlterModelOptions(
            name='certificatelogo',
            options={'verbose_name': 'Logo for attendance certificate', 'verbose_name_plural': 'Logo for attendance certificate'},
        ),
    ]
