# Generated by Django 3.2.18 on 2023-05-04 13:25

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0196_auto_20230705_0716'),
    ]

    operations = [
    ]

