# Generated by Django 3.2.20 on 2023-07-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0197_new_template_IMMERSION_RAPPEL_STR_20230531_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='reminder_notification_sent',
            field=models.BooleanField(blank=True, default=False, verbose_name='Slot reminder notification sent'),
        ),
    ]
