# Generated by Django 3.2.19 on 2023-07-10 12:47

from django.db import migrations

def load_mail_template_vars(apps, schema_editor):
    MailTemplateVars = apps.get_model('core', 'MailTemplateVars')

    data = {
        '{{ annee }}': 'Année',
        '{{ cours.formation }}': 'Formation liée au cours',
        '{{ cours.libelle }}': 'Libellé du cours',
        '{{ cours.nbplaceslibre }}': 'Places disponibles dans le cours',
        '{{ creneau.batiment.libelle }}': 'Créneau : nom du bâtiment',
        '{{ creneau.batiment.lien }}': 'Créneau : lien du bâtiment',
        '{{ creneau.campus }}': 'Créneau : campus',
        '{{ creneau.cours.formation }}': 'Formation concernée par le créneau',
        '{{ creneau.cours.libelle }}': 'Créneau : libellé du cours',
        '{{ creneau.cours.type }}': 'Créneau : type de cours',
        '{{ creneau.date }}': 'Créneau : date',
        '{{ creneau.estuncours }}': 'Indique si le créneau est un cours',
        '{{ creneau.estunevenement }}': 'Indique si le créneau est un évènement',
        '{{ creneau.estunevisite }}': 'Indique si le créneau est une visite',
        '{{ creneau.etablissement }}': 'Créneau : établissement organisateur',
        '{{ creneau.evenement.description }}': "Créneau : description de l'évènement hors offre",
        '{{ creneau.evenement.libelle }}': "Créneau : libellé de l'évènement hors offre",
        '{{ creneau.evenement.type }}': "Créneau : type d'évènement hors offre",
        '{{ creneau.heuredebut }}': 'Créneau : heure de début',
        '{{ creneau.heurefin }}': 'Créneau : heure de fin',
        '{{ creneau.info }}': 'Créneau : autres informations',
        '{{ creneau.intervenants }}': 'Liste des intervenants du créneau',
        '{{ creneau.libelle }}': "Créneau : libellé du cours, de la visite ou de l'évènement",
        '{{ creneau.lien }}': "Créneau : lien s'il s'agit d'un créneau à distance",
        '{{ creneau.limite_annulation }}': "Date limite d'annulation de participation à un créneau",
        '{{ creneau.limite_inscription }}': "Date limite d'inscription à un créneau",
        '{{ creneau.listeInscrits }}': "Liste des inscrits (noms, prénoms et établissements d'origine)",
        '{{ creneau.lycee }}': 'Créneau : nom du lycée organisateur',
        '{{ creneau.nbplaceslibres }}': 'Places disponibles dans le créneau',
        '{{ creneau.salle }}': 'Créneau : salle',
        '{{ creneau.structure }}': 'Créneau : nom de la structure organisatrice',
        '{{ creneau.temoindistanciel }}': "Créneau : indique s'il s'agit d'un créneau à distance ou non",
        '{{ creneau.visite.libelle }}': 'Créneau : libellé (objet) de la visite',
        '{{ creneaux.liste }}': 'Affichage de créneaux sous forme de liste',
        '{{ datedenaissance }}': 'Date de naissance de la personne inscrite au créneau',
        '{{ estetudiant }}': 'Indique si le destinataire est étudiant(e)',
        '{{ estintervenant }}': 'Indique si le destinataire est intervenant(e)',
        '{{ estlyceen }}': 'Indique si le destinataire est lycéen(ne)',
        '{{ estreflycee }}': 'Indique si le destinataire est référent(e) de lycée',
        '{{ estrefstructure }}': 'Indique si le destinataire est référent(e) de structure',
        '{{ estvisiteur }}': 'Indique si le destinataire est visiteur',
        '{{ evenement.libelle }}': "Libellé de l'évènement hors offre",
        '{{ evenement.nbplaceslibre }}': "Places disponibles pour l'évènement hors offre",
        '{{ identifiant }}': 'Identifiant',
        '{{ justificatifs_expires }}': 'Liste des justificatifs à renouveler lorsque la fin de validité approche',
        '{{ jourDestructionCptMin }}': 'Date de destruction automatique du compte',
        '{{ lienAssociationComptes }}': "Lien vers la page de validation d'association de comptes intervenants",
        '{{ lienCreneau }}': "Lien vers l'enquête pour l'évaluation du créneau",
        '{{ lienDemandeur }}': "Courriel de l'utilisateur ayant demandé une association de comptes intervenants",
        '{{ lienGlobal }}': "Lien vers l'enquête pour l'évaluation du dispositif",
        '{{ lienMotDePasse }}': 'Lien vers la page de réinitialisation du mot de passe',
        '{{ lienValidation }}': 'Lien vers la page de validation du compte',
        '{{ lycee }}': 'Nom du lycée',
        '{{ motifAnnulation }}': "Motif de l'annulation",
        '{{ nom }}': 'Nom du destinataire',
        '{{ prenom }}': 'Prénom du destinataire',
        '{{ urlPlateforme }}': 'Adresse (URL) de la plateforme',
        '{{ utilisateurcomptelocal }}': "Indique si l'utilisateur(trice) possède un compte local",
        '{{ visite.libelle }}': 'Libellé (objet) de la visite',
        '{{ visite.nbplaceslibre }}': 'Places disponibles pour la visite'
    }

    for code, description in data.items():
        if not MailTemplateVars.objects.filter(code=code).exists():
            MailTemplateVars.objects.create(code=code, description=description)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0199_general_settings_20230710_1156'),
    ]

    operations = [
        migrations.RunPython(load_mail_template_vars)
    ]
