# Generated by Django 3.2.19 on 2023-07-10 13:05

from django.db import migrations

def associate_template_vars(apps, schema_editor):
    MailTemplate = apps.get_model('core', 'MailTemplate')
    MailTemplateVars = apps.get_model('core', 'MailTemplateVars')

    vars = [
        MailTemplateVars.objects.get(code='{{ creneau.limite_annulation }}'),
        MailTemplateVars.objects.get(code='{{ creneau.limite_inscription }}'),
    ]

    for template in MailTemplate.objects.filter(code__startswith='IMMERSION_'):
        for var in vars:
            template.available_vars.add(var)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0200_missing_templatevars_20230710_1447'),
    ]

    operations = [
        migrations.RunPython(associate_template_vars)
    ]
