# Generated by Django 3.2.18 on 2023-07-17 14:17

from django.db import migrations

def initialize_campus_cities(apps, schema_editor):
    Campus = apps.get_model('core', 'Campus')

    for c in Campus.objects.all():
        if not c.city:
            c.city = c.establishment.city
        if not c.zip_code:
            c.zip_code = c.establishment.zip_code
        if not c.department:
            c.department = c.establishment.zip_code[0:2]

        c.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0204_update_slot_reminders_templates'),
    ]

    operations = [
        migrations.RunPython(initialize_campus_cities)
    ]
