# Generated by Django 3.2.19 on 2023-07-19 08:56

from django.db import migrations

def create_campus_city_template_var(apps, schema_editor):
    MailTemplate = apps.get_model('core', 'MailTemplate')
    MailTemplateVars = apps.get_model('core', 'MailTemplateVars')

    try:
        campus_label = MailTemplateVars.objects.get(code__contains="{{ creneau.campus }}")
        campus_label.code = "{{ creneau.campus.libelle }}"
        campus_label.description = "Créneau : campus : libellé"
        campus_label.save()
    except:
        print("Cannot find / update campus label mail template variable")

    try:
        campus_city = MailTemplateVars.objects.get(code="{{ creneau.campus.ville }}")
    except MailTemplateVars.DoesNotExist:
        campus_city = MailTemplateVars.objects.create(
            code="{{ creneau.campus.ville }}",
            description='Créneau : campus : ville'
        )

    try:
        for template in MailTemplate.objects.filter(body__icontains="creneau.campus"):
            template.body = template.body.replace("creneau.campus", "creneau.campus.libelle")
            template.save()
            template.available_vars.add(campus_city)
    except:
        print("Cannot campus city mail template variable")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0205_initialize_campus_cities_20230717_1617'),
    ]

    operations = [
        migrations.RunPython(create_campus_city_template_var)
    ]
