# Generated by TomaB v0.1 (alpha) on 2023-10-05 10:46
from django.db import migrations

def new_information_text(apps, schema_editor):
    texts = apps.get_model('core', 'InformationText')

    if not texts.objects.filter(code='INTRO_OFFER_SEARCH').exists():
        texts.objects.create(
                label = "Texte d'introduction pour le moteur de recherche de créneaux",
                code = "INTRO_OFFER_SEARCH",
                content = "<p>Vous pouvez rechercher ici l'ensemble des cours, évènements ouverts à l'immersion, pour plus de critères vous pouvez cliquer sur recherche avancée.<p>",
                description = "Texte d'introduction en haut de la page du formulaire de recherche de créneaux",
                active = False,
        )


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0207_link_template_variables_20230726_0927'),
    ]

    operations = [
        migrations.RunPython(new_information_text)
    ]
