# Generated by Django 3.2.18 on 2023-10-06 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0208_new_information_text_20231015_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='establishment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='core.establishment', verbose_name='Establishment'),
            preserve_default=False,
        ),
    ]
