# Generated by Django 3.2.18 on 2023-10-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0209_alter_structure_establishment'),
    ]

    operations = [
    ]
