# Generated by Django 3.2.18 on 2023-10-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0208_new_information_text_20231015_1046'),
        ('core', '0210_merge_20231014_1808'),
    ]

    operations = [
    ]
