# Generated by Django 3.2.18 on 2023-10-19 14:37

from django.db import migrations

def add_general_settings(apps, schema_editor):
    GeneralSettings = apps.get_model('core', 'GeneralSettings')

    setting_name = "ATTENDANCE_PDF_INCLUDE_EMAILS"

    parameters = {
        'type': 'boolean',
        'value': False,
        'description': "Inclut les adresses email des lycéens / étudiants / visiteurs sur les listes d'émargement (PDF)"
    }

    if not GeneralSettings.objects.filter(setting=setting_name).exists():
        GeneralSettings.objects.create(setting=setting_name, parameters=parameters)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0211_merge_20231014_1935'),
    ]

    operations = [
        migrations.RunPython(add_general_settings)
    ]
