# Generated by Django 5.0.4 on 2024-04-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0212_general_settings_pdf_emails_20231019_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='allowed_bachelor_mentions',
            field=models.ManyToManyField(blank=True, related_name='+', to='core.bachelormention', verbose_name='Allowed bachelor mentions'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='allowed_bachelor_teachings',
            field=models.ManyToManyField(blank=True, related_name='+', to='core.generalbachelorteaching', verbose_name='Allowed bachelor teachings'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='allowed_bachelor_types',
            field=models.ManyToManyField(blank=True, related_name='+', to='core.bachelortype', verbose_name='Allowed bachelor types'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='allowed_establishments',
            field=models.ManyToManyField(blank=True, related_name='+', to='core.establishment', verbose_name='Allowed establishments'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='allowed_highschool_levels',
            field=models.ManyToManyField(blank=True, related_name='+', to='core.highschoollevel', verbose_name='Allowed high school levels'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='allowed_highschools',
            field=models.ManyToManyField(blank=True, related_name='+', to='core.highschool', verbose_name='Allowed high schools'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='allowed_post_bachelor_levels',
            field=models.ManyToManyField(blank=True, related_name='+', to='core.postbachelorlevel', verbose_name='Allowed post bachelor levels'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='allowed_student_levels',
            field=models.ManyToManyField(blank=True, related_name='+', to='core.studentlevel', verbose_name='Allowed student levels'),
        ),
        migrations.AlterField(
            model_name='training',
            name='url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Website address'),
        ),
    ]
