# Generated by Django 5.0.4 on 2024-04-17 05:58

from django.db import migrations

def create_general_settings(apps, schema_editor):
    GeneralSettings = apps.get_model('core', 'GeneralSettings')

    data = {
        'ACTIVATE_EDUCONNECT': {
            'type': 'boolean',
            'value': False,
            'description': 'Activation de la fédération EDUCONNECT (lycéens)'
        },
        'ACTIVATE_FEDERATION_AGENT': {
            'type': 'boolean',
            'value': False,
            'description': 'Activation de la fédération Agents (secondaire)'
        },
    }

    for setting_name, parameters in data.items():
        if not GeneralSettings.objects.filter(setting=setting_name).exists():
            GeneralSettings.objects.create(setting=setting_name, parameters=parameters)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0215_remove_visit_mail_variables_20240412_1456'),
    ]

    operations = [
        migrations.RunPython(create_general_settings)
    ]
