# Generated by Django 5.0.4 on 2024-04-17 05:58

from django.db import migrations

def create_general_settings(apps, schema_editor):
    GeneralSettings = apps.get_model('core', 'GeneralSettings')

    parameters = {
        'type': 'boolean',
        'value': False,
        'description': "Activation de l'usurpation d'identité pour les utilisateurs non superutilisateurs"
    }

    if not GeneralSettings.objects.filter(setting='ACTIVATE_HIJACK').exists():
        GeneralSettings.objects.create(
            setting='ACTIVATE_HIJACK',
            parameters=parameters
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0216_federations_general_settings'),
    ]

    operations = [
        migrations.RunPython(create_general_settings)
    ]
