# Generated by Django 5.0.4 on 2024-04-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0217_hijack_general_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschool',
            name='uses_agent_federation',
            field=models.BooleanField(default=False, verbose_name='Uses agent identity federation'),
        ),
        migrations.AddField(
            model_name='highschool',
            name='uses_student_federation',
            field=models.BooleanField(default=False, verbose_name='Uses EduConnect student federation'),
        ),
    ]
