# Generated by Django 5.0.4 on 2024-04-18 16:27

from django.db import migrations

def create_general_settings(apps, schema_editor):
    GeneralSettings = apps.get_model('core', 'GeneralSettings')

    data = {
        'ACTIVATE_COHORT': {
            'type': 'boolean',
            'value': False,
            'description': 'Activation des inscriptions en cohorte'
        },
    }

    for setting_name, parameters in data.items():
        if not GeneralSettings.objects.filter(setting=setting_name).exists():
            GeneralSettings.objects.create(setting=setting_name, parameters=parameters)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0218_highschool_uses_agent_federation_and_more'),
    ]

    operations = [
        migrations.RunPython(create_general_settings)
    ]
