# Generated by Django 5.0.4 on 2024-04-18 18:03

from django.db import migrations

def create_mail_templates(apps, schema_editor):
    MailTemplate = apps.get_model('core', 'MailTemplate')

    try:
        immersion_rappel_str = MailTemplate.objects.get(code='IMMERSION_RAPPEL_STR')
    except MailTemplate.DoesNotExist:
        immersion_rappel_str = None

    if immersion_rappel_str:
        try:
            immersion_annulation_str = MailTemplate.objects.get(code='IMMERSION_ANNULATION_STR')
        except MailTemplate.DoesNotExist:
            immersion_annulation_str = MailTemplate.objects.create(
                label="Notification d'annulation d'une inscription après la date limite d'inscription (référent structure)",
                code='IMMERSION_ANNULATION_STR',
                description="Mail envoyé à un ref structure en cas de déinscription après la date de fin d'inscription à un créneau. Le mail sera envoyé uniquement aux référents Structures qui auront accepté l'envoi dans les paramètres.",
                subject="Annulation d'inscription",
                body="<p></p><p>Bonjour {{ prenom }} {{ nom }}, </p><p>Vous avez paramétré de recevoir les notifications pour le {% if creneau.estuncours %}le cours{% elif creneau.estunevenement %}l' évènement{% endif %} organisé par {% if creneau.lycee %}le lycée {{ creneau.lycee }}{% else %}l'établissement {{ creneau.etablissement }}{% if creneau.structure %} - {{ creneau.structure }}{% endif %}{% endif %}.<br></p><p>L'un(e) des participant(e) s'est désinscrit(e) après la date de fin d'inscription du créneau.<br></p>{% if creneau.estuncours %}Formation : {{ creneau.cours.formation }}<br>Cours : {{ creneau.cours.libelle }}<br>Type : {{ creneau.cours.type }}<br>{% elif creneau.estunevenement %}Type d'évènement : {{ creneau.evenement.type }}<br>Intitulé : {{ creneau.evenement.libelle }}<br>Description : {{ creneau.evenement.description }}{% endif %}<br><br>Ce créneau aura lieu le {{ creneau.date }} de {{ creneau.heuredebut }} à {{ creneau.heurefin }}.<br><br>{% if creneau.temoindistanciel %}Il aura lieu en distanciel sur le lien suivant : {{ creneau.lien }}{% else %}<br>{% if creneau.campus.libelle %}Campus : {{ creneau.campus.libelle }}{% endif %}<br>{% if creneau.batiment.libelle %}Bâtiment : {{ creneau.batiment.libelle }}{% endif %}<br>Lieu : {{ creneau.salle }}{% endif %}<br><br>Intervenants :<br>{{ creneau.intervenants }}<br>{% if creneau.info %} Informations complémentaires : {{ creneau.info }}{% endif %}<p>Voici la nouvelle liste des inscrits : <br>{{ creneau.listeInscrits }}</p><p>Cordialement, </p><p>Le service en ligne d'immersions</p>",

                active=True,
            )

        for variable in immersion_rappel_str.available_vars.all():
            immersion_annulation_str.available_vars.add(variable)

    try:
        immersion_rappel_int = MailTemplate.objects.get(code='IMMERSION_RAPPEL_INT')
    except MailTemplate.DoesNotExist:
        immersion_rappel_int = None

    if immersion_rappel_int:
        try:
            immersion_annulation_int = MailTemplate.objects.get(code='IMMERSION_ANNULATION_INT')
        except MailTemplate.DoesNotExist:
            immersion_annulation_int = MailTemplate.objects.create(
                label="Notification d'annulation d'une inscription après la date limite d'inscription (intervenant)",
                code='IMMERSION_ANNULATION_INT',
                description="Mail envoyé à un intervenant en cas de déinscription après la date de fin d'inscription à un créneau.",
                subject="Annulation d'inscription (référent structure)",
                body="<p></p><p>Bonjour {{ prenom }} {{ nom }}, </p><p>Vous avez été désigné comme intervenant sur {% if creneau.estuncours %}le cours{% elif creneau.estunevenement %}l' évènement{% endif %} organisé par {% if creneau.lycee %}le lycée {{ creneau.lycee }}{% else %}l'établissement {{ creneau.etablissement }}{% if creneau.structure %} - {{ creneau.structure }}{% endif %}{% endif %}.<br></p><p>L'un(e) des participant(e) s'est désinscrit(e) après la date de fin d'inscription du créneau.<br></p>{% if creneau.estuncours %}Formation : {{ creneau.cours.formation }}<br>Cours : {{ creneau.cours.libelle }}<br>Type : {{ creneau.cours.type }}<br>{% elif creneau.estunevenement %}Type d'évènement : {{ creneau.evenement.type }}<br>Intitulé : {{ creneau.evenement.libelle }}<br>Description : {{ creneau.evenement.description }}{% endif %}<br><br>Ce créneau aura lieu le {{ creneau.date }} de {{ creneau.heuredebut }} à {{ creneau.heurefin }}.<br><br>{% if creneau.temoindistanciel %}Il aura lieu en distanciel sur le lien suivant : {{ creneau.lien }}{% else %}<br>{% if creneau.campus.libelle %}Campus : {{ creneau.campus.libelle }}{% endif %}<br>{% if creneau.batiment.libelle %}Bâtiment : {{ creneau.batiment.libelle }}{% endif %}<br>Lieu : {{ creneau.salle }}{% endif %}<br><br>Intervenants :<br>{{ creneau.intervenants }}<br>{% if creneau.info %} Informations complémentaires : {{ creneau.info }}{% endif %}<p>Voici la liste des inscrits : <br>{{ creneau.listeInscrits }}</p><p>Cordialement, </p><p>Le service en ligne d'immersions</p><p></p>",
                active=True,
            )

        for variable in immersion_rappel_int.available_vars.all():
            immersion_annulation_int.available_vars.add(variable)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0219_new_setting_activate_cohort'),
    ]

    operations = [
        migrations.RunPython(create_mail_templates)
    ]
