# Generated by Django 5.0.4 on 2024-04-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0223_generalsettings_setting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschool',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
