# Generated by Django 5.0.4 on 2024-04-25 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0223_generalsettings_setting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='registration_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Registrations end date'),
        ),
        migrations.AddField(
            model_name='period',
            name='registration_end_date_policy',
            field=models.SmallIntegerField(choices=[(0, 'Use this period regisration end date'), (1, 'Use slots registration end dates')], default=1, verbose_name='Registration end date policy'),
        ),
        migrations.AddField(
            model_name='slot',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.period', verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='period',
            name='registration_start_date',
            field=models.DateTimeField(verbose_name='Registrations start date'),
        ),
    ]
