# Generated by Django 5.0.4 on 2024-04-25 14:25

from django.db import migrations

def assign_period_to_slot(apps, schema_editor):
    Period = apps.get_model('core', 'Period')
    Slot = apps.get_model('core', 'Slot')

    for slot in Slot.objects.filter(period__isnull=True):
        try:
            period = Period.objects.filter(
                immersion_start_date__lte=slot.date,
                immersion_end_date__gte=slot.date
            ).first()

            slot.period = period
            slot.save()
        except:
            # No period
            print(f"Can't find a valid period for slot {slot.pk} ({slot.date})")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0224_period_registration_end_date_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_period_to_slot),
    ]
