# Generated by Django 5.0.4 on 2024-05-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0224_alter_highschool_email'),
        ('core', '0225_assign_period_to_slot'),
    ]

    operations = [
    ]
