# Generated by Django 5.0.4 on 2024-05-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0228_period_cancellation_limit_delay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='cancellation_limit_delay',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Will be relative to each slot of this period', null=True, verbose_name='Cancellation limit delay'),
        ),
        migrations.AlterField(
            model_name='period',
            name='registration_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin des inscriptions pour la période'),
        ),
        migrations.AlterField(
            model_name='period',
            name='registration_end_date_policy',
            field=models.SmallIntegerField(choices=[(0, 'Use this period settings'), (1, 'Use slots settings')], default=1, verbose_name='Registration end date and delay policy'),
        ),
        migrations.AlterField(
            model_name='period',
            name='registration_start_date',
            field=models.DateTimeField(verbose_name='Date de début des inscriptions pour la période'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='allow_group_registrations',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Allow group registrations'),
        ),
    ]
