# Generated by Django 5.0.4 on 2024-05-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0229_alter_period_cancellation_limit_delay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='allow_group_registrations',
            field=models.BooleanField(default=False, null=True, verbose_name='Allow group registrations'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='allow_individual_registrations',
            field=models.BooleanField(default=True, null=True, verbose_name='Allow individual registrations'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='group_mode',
            field=models.SmallIntegerField(choices=[(0, 'One group'), (1, 'By number of places')], default=0, null=True, verbose_name='Group mode'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='public_group',
            field=models.BooleanField(null=True, verbose_name='Public group registrations'),
        ),
    ]
