# Generated by Django 5.0.4 on 2024-05-17 06:38

from django.db import migrations

def set_slot_fields(apps, schema_editor):
    Slot = apps.get_model('core', 'Slot')

    Slot.objects.all().update(
        allow_group_registrations=False,
        allow_individual_registrations=True,
        public_group=False,
        n_group_places=None
    )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0231_alter_slot_allow_group_registrations_and_more'),
    ]

    operations = [
        migrations.RunPython(set_slot_fields),
    ]
