# Generated by Django 5.0.4 on 2024-05-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0232_set_slot_group_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='immersiongrouprecord',
            name='attendance_status',
            field=models.SmallIntegerField(choices=[(0, 'Not entered'), (1, 'Present'), (2, 'Absent')], default=0, verbose_name='Attendance status'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='public_group',
            field=models.BooleanField(default=False, verbose_name='Public group registrations'),
        ),
    ]
