# Generated by Django 5.0.4 on 2024-05-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0233_immersiongrouprecord_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canceltype',
            name='groups',
            field=models.BooleanField(default=False, verbose_name='Usable for groups'),
        ),
        migrations.AddField(
            model_name='canceltype',
            name='students',
            field=models.BooleanField(default=True, verbose_name='Usable for students'),
        ),
    ]
