# Generated by Django 5.0.6 on 2024-06-03 11:07

from django.db import migrations

def load_mail_template_vars(apps, schema_editor):
    MailTemplateVars = apps.get_model('core', 'MailTemplateVars')

    data = {
        '{{ destinataire.estCohorte }}': 'Indique si le destinataire est un groupe',
        '{{ destinataire.estIndividu }}': 'Indique si le destinataire est un individu',
        '{{ creneau.listeCohortes }}': 'Liste des groupes inscrits au créneau',
        '{{ cohorte.etablissementInscrit }}': "Groupe : nom de l'établissement scolaire",
        '{{ cohorte.nbEleves }}': "Groupe : nombre d'élèves inscrits",
        '{{ cohorte.nbAccompagnateurs }}': "Groupe : nombre d'accompagnateurs inscrits",
        '{{ cohorte.nbPlaces }}': "Groupe : nombre total de places prises par le groupe",
        '{{ cohorte.fichierJoint }}': "Groupe : lien vers un éventuel fichier joint",
        '{{ cohorte.commentaires }}': "Groupe : commentaires éventuels",
    }

    for code, description in data.items():
        if not MailTemplateVars.objects.filter(code=code).exists():
            MailTemplateVars.objects.create(code=code, description=description)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0234_canceltype_groups_canceltype_students'),
    ]

    operations = [
        migrations.RunPython(load_mail_template_vars)
    ]
