# Generated by Django 5.0.6 on 2024-06-09 11:24

from django.db import migrations

def load_mail_template_vars(apps, schema_editor):
    MailTemplateVars = apps.get_model('core', 'MailTemplateVars')

    data = {
        '{{ educonnect }}': 'Indique si le lycée renseigné dans la fiche utilise la fédération ÉduConnect',
    }

    for code, description in data.items():
        if not MailTemplateVars.objects.filter(code=code).exists():
            MailTemplateVars.objects.create(code=code, description=description)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0235_new_groups_template_vars'),
    ]

    operations = [
        migrations.RunPython(load_mail_template_vars)
    ]