# Generated by Django 5.0.6 on 2024-06-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0236_new_educonnect_template_var'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschool',
            name='uai_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='UAI Code'),
        ),
    ]
