# Generated by Django 5.0.6 on 2024-06-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0237_highschool_uai_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MefStat',
            fields=[
                ('code', models.CharField(primary_key=True, serialize=False, verbose_name='Code')),
                ('label', models.CharField(max_length=256, verbose_name='Label')),
            ],
            options={
                'verbose_name': 'MefStat - High school level',
                'verbose_name_plural': 'MefStat - High school levels',
            },
        ),
    ]
