# Generated by Django 5.0.6 on 2024-06-24 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0238_mefstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mefstat',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mefstat', to='core.highschoollevel', verbose_name='Level'),
            preserve_default=False,
        ),
    ]
