# Generated by Django 5.0.6 on 2024-07-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0239_mefstat_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAI',
            fields=[
                ('uai_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='UAI Code')),
                ('label', models.CharField(blank=True, max_length=512, null=True, verbose_name='Label')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='City')),
                ('academy', models.CharField(blank=True, max_length=128, null=True, verbose_name='City')),
            ],
            options={
                'verbose_name': 'Establishment with UAI',
                'verbose_name_plural': 'Establishments with UAI',
                'ordering': ['city', 'label'],
            },
        ),
    ]
