# Generated by Django 5.0.6 on 2024-07-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0240_uai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highschool',
            name='uai_code',
        ),
        migrations.AddField(
            model_name='highschool',
            name='uai_code',
            field=models.ManyToManyField(blank=True, related_name='highschools', to='core.uai', verbose_name='UAI Code'),
        ),
    ]
