# Generated by Django 5.0.4 on 2024-07-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0241_remove_highschool_uai_code_highschool_uai_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='is_host_establishment',
            field=models.BooleanField(default=True, verbose_name='Is host establishment'),
        ),
    ]
