# Generated by Django 5.0.6 on 2024-07-02 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0242_establishment_is_host_establishment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highschool',
            old_name='uai_code',
            new_name='uai_codes',
        ),
        migrations.RenameField(
            model_name='uai',
            old_name='uai_code',
            new_name='code',
        ),
    ]
