# Generated by Django 5.0.6 on 2024-07-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0243_rename_uai_code_highschool_uai_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='place',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Face to face'), (1, 'Remote'), (2, 'Outside of host establishment')], default=0, verbose_name='Place'),
        ),
    ]
