# Generated by Django 5.0.6 on 2024-07-02 13:03

from django.db import migrations

def update_slots(apps, schema_editor):
    Slot = apps.get_model('core', 'Slot')
    Slot.objects.filter(face_to_face=True).update(place=0)
    Slot.objects.filter(face_to_face=False).update(place=1)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0244_slot_place'),
    ]

    operations = [
        migrations.RunPython(update_slots)
    ]
