# Generated by Django 5.0.6 on 2024-07-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0245_update_existing_slot_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='face_to_face',
        ),
    ]
