# Generated by Django 5.0.6 on 2024-07-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0247_remove_highschool_visit_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='canceltype',
            name='managers',
            field=models.BooleanField(default=False, verbose_name='Reserved for Managers'),
        ),
        migrations.AlterField(
            model_name='canceltype',
            name='system',
            field=models.BooleanField(default=False, verbose_name='Reserved for System'),
        ),
    ]
