# Generated by Django 5.0.7 on 2024-07-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0249_add_information_text_intro_offer_cohort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canceltype',
            name='groups',
            field=models.BooleanField(default=False, verbose_name='Usable for groups registrations'),
        ),
        migrations.AlterField(
            model_name='canceltype',
            name='students',
            field=models.BooleanField(default=True, verbose_name='Usable for individual registrations'),
        ),
        migrations.AlterField(
            model_name='immersiongrouprecord',
            name='emails',
            field=models.TextField(blank=True, null=True, verbose_name='Emails'),
        ),
    ]
