# Generated by Django 5.0.7 on 2024-07-24 08:06

from django.db import migrations

def remove_visit_intro(apps, schema_editor):
    InformationText = apps.get_model('core', 'InformationText')
    InformationText.objects.filter(code='INTRO_VISITE').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0250_alter_canceltype_groups_alter_canceltype_students_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_visit_intro),
    ]
