# Generated by Django 5.0.7 on 2024-09-06 19:06
from django.db import migrations, models
from immersionlyceens.apps.core.models import InformationText


def population_information_text(apps, schema_editor):
    InformationText = apps.get_model('core', "InformationText")

    if not InformationText.objects.filter(code='INTRO_HIGHSCHOOL_CONNECTION').exists():
        InformationText.objects.create(
            label="Texte d'information pour la connexion des lycéens",
            code="INTRO_HIGHSCHOOL_CONNECTION",
            content="",
            description="Texte d'information pour la connexion des lycéens (choix EduConnect ou non)",
            active=True,
        )

    if not InformationText.objects.filter(code='INTRO_AGENT_CONNECTION').exists():
        InformationText.objects.create(
            label="Texte d'information pour la connexion des agents lycée",
            code="INTRO_AGENT_CONNECTION",
            content="",
            description="Texte d'information pour la connexion des agents lycée (référents et intervenants)",
            active=True,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0253_general_settings_active_modif_masse'),
    ]

    operations = [
        migrations.RunPython(population_information_text),
    ]
