# Generated by Django 5.0.7 on 2024-09-20 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0254_add_information_texts_for_connections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immersionuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits, @/./+/-/_/!/: and / only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w. @:/!+-]+$', 'Enter a valid username.', 'invalid')], verbose_name='username'),
        ),
    ]
