# Generated by Django 5.0.9 on 2024-10-11 09:46

import immersionlyceens.libs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0255_alter_immersionuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='immersionuser',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, null=True, validators=[immersionlyceens.libs.validators.JsonSchemaValidator('/home/karma/projets/immersion-v4/immersionlyceens/apps/core/schemas/general_settings.json')], verbose_name='User preferences'),
        ),
    ]
