# Generated by Django 5.0.9 on 2024-10-14 09:31

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0255_alter_immersionuser_username'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='immersion',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('student', 'slot'), name='unique_student_slot'),
        ),
    ]
