# Generated by Django 5.0.9 on 2024-10-11 09:46
from os.path import dirname, join
import immersionlyceens.libs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0255_alter_immersionuser_username'),
    ]

    schema_path = join(dirname(dirname(__file__)), 'schemas', 'general_settings.json')

    operations = [
        migrations.AddField(
            model_name='immersionuser',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, null=True, validators=[immersionlyceens.libs.validators.JsonSchemaValidator(schema_path)], verbose_name='User preferences'),
        ),
    ]
