# Generated by Django 5.0.9 on 2024-10-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0256_immersion_unique_student_slot'),
        ('core', '0256_immersionuser_preferences'),
    ]

    operations = [
    ]
