# Generated by Django 5.0.9 on 2025-01-10 13:52

from django.db import migrations

def rename_twitter_setting(apps, schema_editor):
    GeneralSettings = apps.get_model('core', "GeneralSettings")

    try:
        twitter_setting = GeneralSettings.objects.get(setting="TWITTER_ACCOUNT_URL")

        twitter_setting.setting = "SOCIAL_NETWORK_URL"

        parameters = twitter_setting.parameters
        parameters['description'] = "Adresse du fil d'actualités"

    except GeneralSettings.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0257_merge_20241015_1345'),
    ]

    operations = [
        migrations.RunPython(rename_twitter_setting),
    ]
