# Generated by Django 5.0.11 on 2025-02-03 08:21

from django.db import migrations

def create_general_settings(apps, schema_editor):
    GeneralSettings = apps.get_model('core', 'GeneralSettings')

    data = {
        'MAX_SLOT_PLACES': {
            'type': 'integer',
            'value': 200,
            'description': 'Nombre maximal de places pour un créneau (cours ou événement)'
        },
    }

    for setting_name, parameters in data.items():
        if not GeneralSettings.objects.filter(setting=setting_name).exists():
            GeneralSettings.objects.create(
                setting=setting_name,
                parameters=parameters,
                setting_type=1
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0258_rename_twitter_setting'),
    ]

    operations = [
        migrations.RunPython(create_general_settings)
    ]

