# Generated by Django 5.0.14 on 2025-06-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0259_max_slot_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorType',
            fields=[
                ('code', models.CharField(primary_key=True, serialize=False, verbose_name='Code')),
                ('label', models.CharField(max_length=256, unique=True, verbose_name='Label')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Visitor type',
                'verbose_name_plural': 'Visitor types',
            },
        ),
        migrations.AlterField(
            model_name='establishment',
            name='data_source_plugin',
            field=models.CharField(blank=True, choices=[('LDAP', 'LDAP'), ('REST', 'REST')], max_length=256, null=True, verbose_name='Accounts source plugin'),
        ),
    ]
