# Generated by Django 5.0.14 on 2025-07-09 05:39
from django.db import migrations

def add_disability_setting(apps, schema_editor):
    GeneralSettings = apps.get_model('core', "GeneralSettings")

    code = 'ACTIVATE_DISABILITY'
    setting_type = 1 # FUNCTIONAL - can't access 'GeneralSettings.FUNCTIONAL' here

    if not GeneralSettings.objects.filter(setting=code).exists():
        GeneralSettings.objects.create(
            setting=code,
            parameters={
                "type": "object",
                "value": {
                    "activate": False,
                    "form_sentence": "Je déclare être atteint(e) d'un handicap nécessitant un accompagnement lors des immersions"
                },
                "description": "Activation de la gestion du handicap pour les inscrits"
            },
            setting_type=setting_type
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0259_max_slot_place'),
    ]

    operations = [
        migrations.RunPython(add_disability_setting),
    ]
