# Generated by Django 5.0.14 on 2025-07-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0260_add_handicap_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='disability_notify_on_record_validation',
            field=models.BooleanField(blank=True, default=True, help_text='Notify disability referent on record validation', null=True, verbose_name='Disability referent record notification'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='disability_notify_on_slot_registration',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Never'), (1, 'Always, if the registrant checked the disability flag'), (2, 'At the request of the registrant for the slot')], default=0, help_text='Notify disability referent on slot registration', null=True, verbose_name='Disability slot notification'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='disability_referent_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Disability referent email'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='data_source_plugin',
            field=models.CharField(blank=True, choices=[('LDAP', 'LDAP'), ('REST', 'REST')], max_length=256, null=True, verbose_name='Accounts source plugin'),
        ),
    ]
