# Generated by Django 5.0.14 on 2025-07-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0262_alter_establishment_disability_notify_on_record_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='disability_notify_on_slot_registration',
            field=models.SmallIntegerField(choices=[(0, 'Never'), (1, 'Always, if the registrant checked the disability flag'), (2, 'At the request of the registrant for the slot')], default=0, help_text='Notify disability referent on slot registration', verbose_name='Disability slot notification'),
        ),
    ]
