# Generated by Django 5.0.14 on 2025-07-10 09:58
from django.db import migrations

def add_template_vars(apps, schema_editor):
    MailTemplateVars = apps.get_model('core', "MailTemplateVars")

    vars = {
        "{{ inscrit.prenom }}": "Prénom de la personne pour qui la fiche vient d'être validée ou qui vient de s'inscrire à un créneau",
        "{{ inscrit.nom }}": "Nom de la personne pour qui la fiche vient d'être validée ou qui vient de s'inscrire à un créneau",
        "{{ inscrit.email }}": "Email de la personne pour qui la fiche vient d'être validée ou qui vient de s'inscrire à un créneau",
        "{{ inscrit.aDeclareHandicap }}": "'True' si la personne inscrite à un créneau a coché la case Handicap dans sa fiche"
    }

    for code, description in vars.items():
        if not MailTemplateVars.objects.filter(code=code).exists():
            MailTemplateVars.objects.create(
                code=code,
                description=description,
            )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0263_alter_establishment_disability_notify_on_slot_registration'),
    ]

    operations = [
        migrations.RunPython(add_template_vars),
    ]
