# Generated by Django 5.0.14 on 2025-07-09 12:54

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0263_alter_establishment_disability_notify_on_slot_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschool',
            name='disability_notify_on_record_validation',
            field=models.BooleanField(default=True, help_text='Notify disability referent on record validation', verbose_name='Disability referent record notification'),
        ),
        migrations.AddField(
            model_name='highschool',
            name='disability_notify_on_slot_registration',
            field=models.SmallIntegerField(choices=[(0, 'Never'), (1, 'Always, if the registrant checked the disability flag'), (2, 'At the request of the registrant for the slot')], default=0, help_text='Notify disability referent on slot registration', verbose_name='Disability slot notification'),
        ),
        migrations.AddField(
            model_name='highschool',
            name='disability_referent_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Disability referent email'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='label',
            field=models.CharField(max_length=256, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='label',
            field=models.CharField(max_length=256, verbose_name='Label'),
        ),
        migrations.AddConstraint(
            model_name='establishment',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('label',), name='unique_establishment_label'),
        ),
    ]
