# Generated by Django 5.0.14 on 2025-07-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0264_highschool_disability_notify_on_record_validation_and_more'),
        ('core', '0266_link_disability_related_mail_templates_vars'),
    ]

    operations = [
    ]
