# Generated by Django 5.0.14 on 2025-07-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0267_merge_20250711_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='refstructuresnotificationssettings',
            name='disability_structures',
            field=models.ManyToManyField(blank=True, related_name='structures_disabled_notifications', to='core.structure', verbose_name='Selected structures for disabled registrants notifications'),
        ),
        migrations.AlterField(
            model_name='refstructuresnotificationssettings',
            name='structures',
            field=models.ManyToManyField(blank=True, related_name='source_structures', to='core.structure', verbose_name='Selected structures for registrants list'),
        ),
    ]
