# Generated by Django 5.0.14 on 2025-06-25 14:06
from warnings import catch_warnings

from django.db import migrations

data = {

        'HIDE_FIELDS_PUBLIC_AREA': {
            "type": "object",
            "value": {
                "speakers": {
                    "hide_public_area": False,
                    "hide_after_registration": False
                },
                "meeting_place": {
                    "hide_public_area": False,
                    "hide_after_registration": False
                },
                "building": {
                    "hide_public_area": False,
                    "hide_after_registration": False
                },
                "structure": {
                    "hide_public_area": False,
                    "hide_after_registration": False
                }
            },
            "description": "Masquer les champs en partie publique et/ou après inscription"
        },

    }

def create_general_settings(apps, schema_editor):
    general_settings = apps.get_model('core', 'GeneralSettings')

    for setting_name, parameters in data.items():
        if not general_settings.objects.filter(setting=setting_name).exists():
            general_settings.objects.create(setting=setting_name, parameters=parameters)

def remove_general_settings(apps, schema_editor):
    general_settings = apps.get_model('core', 'GeneralSettings')
    try:
        general_settings.objects.get(setting=list(data.keys())[0]).delete()
    except general_settings.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0259_max_slot_place'),
    ]

    operations = [
        migrations.RunPython(create_general_settings, reverse_code=remove_general_settings),
    ]
