# Generated by Django 5.0.14 on 2025-07-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0268_refstructuresnotificationssettings_disability_structures_and_more'),
        ('core', '0269_hide_fields_public_parameter'),
    ]

    operations = [
    ]
