# Generated by Django 5.0.14 on 2025-07-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0270_visitortype_alter_establishment_data_source_plugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestationdocument',
            name='visitor_types',
            field=models.ManyToManyField(blank=True, related_name='attestations', to='core.visitortype', verbose_name='Visitor types'),
        ),
    ]
