# Generated by Django 5.0.14 on 2025-08-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0271_attestationdocument_visitor_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='immersionuser',
            name='email_change_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email change date'),
        ),
        migrations.AddField(
            model_name='immersionuser',
            name='email_validation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email activation date'),
        ),
    ]
