# Generated by Django 5.0.14 on 2025-09-01 09:21

from django.db import migrations

def load_scheduled_tasks(apps, schema_editor):
    ScheduledTask = apps.get_model('core', 'ScheduledTask')

    if not ScheduledTask.objects.filter(command_name='annual_purge').exists():
        ScheduledTask.objects.create(
            command_name="annual_purge",
            description="Purge annuelle",
            active=False,
            date=None,
            time="11:00",
            frequency=None,
            monday=False,
            tuesday=False,
            wednesday=False,
            thursday=False,
            friday=False,
            saturday=False,
            sunday=False
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0273_new_social_network_url_param'),
    ]

    operations = [
        migrations.RunPython(load_scheduled_tasks)
    ]
