# Generated by Django 5.0.14 on 2025-09-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0271_course_end_date_course_start_date'),
        ('core', '0274_purge_scheduled_task'),
    ]

    operations = [
    ]
