# Generated by Django 5.0.14 on 2025-09-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0275_merge_20250903_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='offofferevent',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Immersions end date'),
        ),
        migrations.AddField(
            model_name='offofferevent',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Immersions start date'),
        ),
        migrations.AlterField(
            model_name='attestationdocument',
            name='visitor_types',
            field=models.ManyToManyField(blank=True, help_text='Optional: when visitor profile is selected, you may select one or more visitor types', limit_choices_to={'active': True}, related_name='attestations', to='core.visitortype', verbose_name='Visitor types'),
        ),
    ]
