# Generated by Django 5.0.14 on 2025-09-03 19:33

from django.db import migrations

def add_template_vars(apps, schema_editor):
    MailTemplateVars = apps.get_model('core', "MailTemplateVars")

    code = "motifRejetCompte"

    if not MailTemplateVars.objects.filter(code=code).exists():
        MailTemplateVars.objects.create(
            code=code,
            description="Motif de rejet d'un compte",
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0276_offofferevent_end_date_offofferevent_start_date_and_more'),
    ]

    operations = [
        migrations.RunPython(add_template_vars),
    ]
