# Generated by Django 5.0.14 on 2025-09-03 19:38

from django.db import migrations

def associate_template_vars(apps, schema_editor):
    MailTemplate = apps.get_model('core', 'MailTemplate')
    MailTemplateVars = apps.get_model('core', 'MailTemplateVars')

    try:
        template = MailTemplate.objects.get(code='CPT_MIN_REJET')
        code = "motifRejetCompte"
        var = MailTemplateVars.objects.get(code__iexact=code)
        template.available_vars.add(var)
    except MailTemplate.DoesNotExist:
        print("Mail template CPT_MIN_REJET does not exist")
    except MailTemplateVars.DoesNotExist:
        print("Mail template variable %s does not exist" % code)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0277_new_motifrejet_mail_template_var'),
    ]

    operations = [
        migrations.RunPython(associate_template_vars),
    ]
