# Generated by Django 5.0.14 on 2025-09-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0278_link_motifrejet_var_to_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Immersions end date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Immersions start date'),
        ),
    ]
