# Generated by Django 5.0.14 on 2025-09-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0279_alter_course_end_date_alter_course_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offofferevent',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Immersions end date'),
        ),
        migrations.AlterField(
            model_name='offofferevent',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Immersions start date'),
        ),
    ]
