# Generated by Django 5.0.14 on 2025-09-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0280_alter_offofferevent_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='first_slot_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='last_slot_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offofferevent',
            name='first_slot_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offofferevent',
            name='last_slot_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
