# Generated by Django 3.2.19 on 2023-07-11 06:57

from django.db import migrations

def load_mail_templates(apps, schema_editor):
    MailTemplate = apps.get_model('core', 'MailTemplate')
    MailTemplateVars = apps.get_model('core', 'MailTemplateVars')

    data = {
        'CPT_MIN_REJET': {
            'label': 'Mail rejet compte lycéen ou visiteur',
            'description': 'Mail envoyé lors du rejet d’un compte',
            'subject': 'Rejet de votre compte Immersion',
            "body": "<p></p><p>Bonjour {{ prenom }} {{ nom }},</p><p>{% if estlyceen %}Votre compte immersion a été rejeté par le lycée que vous avez choisi.</p><p>Merci de contacter votre lycée ou de renseigner le bon lycée. {% elif estvisiteur %}<br></p><p>Votre compte immersion a été rejeté par le référent Immersion. </p>Merci de nous contacter afin de discuter de vos motivations.{% endif %}{% if motifRejetCompte %}<br><p>{{ motifRejetCompte }}</p>{% endif %}<br><p></p><p></p><p>Cordialement, </p><p>Le service en ligne d'immersions</p><p><br></p><p></p>",
            'active': True,
            'available_vars': [
                '{{ annee }}',
                '{{ estlyceen }}',
                '{{ estvisiteur }}',
                '{{ inscrit.prenom }}',
                '{{ nom }}',
                '{{ prenom }}',
                '{{ urlPlateforme }}',
                '{{ motifRejetCompte }}'
            ]
        },
    }

    for code, template in data.items():
        try:
            mt = MailTemplate.objects.get(code=code)
            mt.body = template['body']
            mt.available_vars.clear()
            mt.save()
        except MailTemplate.DoesNotExist:
            mt = MailTemplate.objects.create(
                code=code,
                label=template['label'],
                description=template['description'],
                active=template['active'],
                subject=template['subject'],
                body=template['body'],
            )

        for var in MailTemplateVars.objects.filter(code__in=template['available_vars']):
            mt.available_vars.add(var.id)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0282_rename_twitter_to_x'),
    ]

    operations = [
        migrations.RunPython(load_mail_templates),
    ]
