# Generated by Django 5.0.14 on 2025-10-13 05:46

from django.db import migrations

def load_scheduled_tasks(apps, schema_editor):
    ScheduledTask = apps.get_model('core', 'ScheduledTask')

    if not ScheduledTask.objects.filter(command_name='import_uai').exists():
        ScheduledTask.objects.create(
            command_name="import_uai",
            description="Renouvellement des UAI",
            active=False,
            date=None,
            time="11:00",
            frequency=None,
            monday=False,
            tuesday=False,
            wednesday=False,
            thursday=False,
            friday=False,
            saturday=False,
            sunday=False
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0283_new_cpt_min_rejet'),
    ]

    operations = [
        migrations.RunPython(load_scheduled_tasks)
    ]
