# Generated by Django 5.0.14 on 2026-02-18 08:40

import immersionlyceens.apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0284_uai_update_scheduled_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='immersiongrouprecord',
            name='manager',
            field=models.TextField(blank=True, null=True, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='certificatelogo',
            name='logo',
            field=models.ImageField(help_text='Uniquement des fichiers de type (gif, jpg, png, svg+xml)', upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='certificatesignature',
            name='signature',
            field=models.ImageField(help_text='Uniquement des fichiers de type (gif, jpg, png, svg+xml)', upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='customthemefile',
            name='file',
            field=models.FileField(help_text='Uniquement des fichiers de type (svg+xml, png, jpeg, jpg, ico, css, js). Taille max : 20,0\xa0Mio', upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='logo',
            field=models.ImageField(blank=True, help_text='Uniquement des fichiers de type (gif, jpg, png, svg+xml)', null=True, upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='signature',
            field=models.ImageField(blank=True, help_text='Uniquement des fichiers de type (gif, jpg, png, svg+xml)', null=True, upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='logo',
            field=models.ImageField(blank=True, help_text='Uniquement des fichiers de type (gif, jpg, png, svg+xml)', null=True, upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='signature',
            field=models.ImageField(blank=True, help_text='Uniquement des fichiers de type (gif, jpg, png, svg+xml)', null=True, upload_to=immersionlyceens.apps.core.models.get_file_path, verbose_name='Signature'),
        ),
    ]
