# Generated by Django 5.0.14 on 2026-02-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0285_immersiongrouprecord_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immersiongrouprecord',
            name='manager',
            field=models.TextField(default='Manager ?', verbose_name='Manager'),
        ),
    ]
