# Generated by Django 5.0.14 on 2026-02-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0286_alter_immersiongrouprecord_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immersiongrouprecord',
            name='manager',
            field=models.TextField(default='', verbose_name='Manager'),
        ),
    ]
