# Generated by Django 3.2.8 on 2022-02-24 10:03

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0132_auto_20220211_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDepartmentStaff',
            fields=[
                ('immersionuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.immersionuser')),
            ],
            options={
                'verbose_name': 'Legal department staff',
                'verbose_name_plural': 'Legal department staffs',
            },
            bases=('core.immersionuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentManager',
            fields=[
            ],
            options={
                'verbose_name': 'Establishment manager',
                'verbose_name_plural': 'Establishment managers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.immersionuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HighSchoolManager',
            fields=[
            ],
            options={
                'verbose_name': 'High school manager',
                'verbose_name_plural': 'High school managers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.immersionuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HighSchoolStudent',
            fields=[
            ],
            options={
                'verbose_name': 'High school student',
                'verbose_name_plural': 'High school students',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.immersionuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MasterEstablishmentManager',
            fields=[
            ],
            options={
                'verbose_name': 'Master establishment manager',
                'verbose_name_plural': 'Master establishment managers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.immersionuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
            ],
            options={
                'verbose_name': 'Operator',
                'verbose_name_plural': 'Operators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.immersionuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.immersionuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StructureManager',
            fields=[
            ],
            options={
                'verbose_name': 'Structure manager',
                'verbose_name_plural': 'Stucture managers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.immersionuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.immersionuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.immersionuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
