# Generated by Django 3.2.8 on 2022-02-24 10:10

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_auto_20220211_0959'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authtoken', '0003_tokenproxy'),
        ('immersion', '0027_remove_visitorrecord_civility'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegalDepartmentStaff',
        ),
        migrations.CreateModel(
            name='LegalDepartmentStaff',
            fields=[
            ],
            options={
                'verbose_name': 'Legal department staff',
                'verbose_name_plural': 'Legal department staffs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.immersionuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
