# Generated by Django 3.2.8 on 2022-03-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_unaccent_extension'),
        ('user', '0002_auto_20220224_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
            ],
            options={
                'verbose_name': 'User group',
                'verbose_name_plural': 'User groups',
                'ordering': ['pk'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.immersionusergroup',),
        ),
    ]
