# Generated by Django 3.2.18 on 2023-03-31 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usergroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structuremanager',
            options={'verbose_name': 'Structure manager', 'verbose_name_plural': 'Structure managers'},
        ),
    ]
