# Generated by Django 3.2.18 on 2023-04-11 07:24

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_add_cons_str_group'),
        ('user', '0004_alter_structuremanager_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureConsultant',
            fields=[
            ],
            options={
                'verbose_name': 'Structure consultant',
                'verbose_name_plural': 'Structure consultants',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.immersionuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
